### ISSUE TITLE
New Creality Firmware V1.3.2.1 compatibility

### ISSUE THREAD

**Issue by sendorm** [Guilouz/Creality-K1-and-K1-Max#10]
With the onset of new open source firmware more people would be liking to upgrade their moonraker and fluidd. 
But creality have changed the locations of their installs.

On the new firmware moonraker resides at /usr/data/moonraker. 
So the second step of upgrading moonraker should be 

`cd /usr/data/moonraker`

**Comment by Guilouz** [comment]
Don't worry I working to update my Wiki for the new firmware.

<img width="454" alt="Capture d’écran 2023-09-13 à 22 50 23" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/d22d55c9-ea34-40cd-a5e8-b99e80bba138">
