### ISSUE TITLE
KAMP line purge ignoring supports.

### ISSUE THREAD

**Issue by grrminator** [Guilouz/Creality-K1-and-K1-Max#100]
### What happened?

![20231108_141130](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/28405754/af0af04e-06dd-4de9-b943-09da14e4b36e)

Image here. I know I can change the distance from the model in the CFG. But why does it ignore the support placement (the rings) there?

Is my only option editing the CFG?

### What did you expect to happen instead?

KAMP to know there is a support there

### How to reproduce this issue?

Use a model with support placement where the line purge MAY occur

**Comment by grrminator** [comment]
Like id prefer not to edit the CFG so I can keep it at 10 if I printa big model. Shouldnt the purge be moveable or a little smarter? or does it genuinely not "know" a support is there?

**Comment by Guilouz** [comment]
I think KAMP is not the problem here because KAMP uses the exclude_object function which indicates the dimensions of the model, this is given by the slicer.

What slicer do you use?

**Comment by grrminator** [comment]
Orcaslicer

**Comment by grrminator** [comment]
That circle is NOT the model. The purge line IS 10mm from the model. That circle is the first layer of a tree there

**Comment by Guilouz** [comment]
Yes I have understand but slicer include supports to define area for cancel object.

posibble annissue in orcaslicer build, wich version do you use?

maybe you can try with another slicer to see.

**Comment by grrminator** [comment]
I could check but would have to generate a profile

**Comment by grrminator** [comment]
I could also give you the model to slice and see if it does it with you?

**Comment by grrminator** [comment]
https://www.thingiverse.com/thing:6285690/files

**Comment by grrminator** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/2671 I raised an issue in orcaslicer based off this guys discussion. It appears it MAY be orca slicer. Which is disappointing.

**Comment by Noisyfox** [comment]
If KAMP reads the boundary directly from EXCLUDE_OBJECT_DEFINE then that's the problem as the outline given from this command contains only the model outline but not support. Not sure if this is standard since PrusaSlicer does not include support in this command as well.

**Comment by grrminator** [comment]
"The wipe/prime tower shouldn't be exposed to Klipper object exclusion feature. KAMP get printable size via object cancellation definition is hacky and against the intended use of object cancellation IMHO. It would be better to pass the minimum and maximum positions from slicer to it if KAMP supported, as is done with other adaptive bed mesh methods.  You might want to consider using https://github.com/eamars/klipper_adaptive_bed_mesh or https://github.com/Turge08/print_area_bed_mesh for better adaptive bed mesh management"

Per @Noisyfox above, this is the only way to fix it but im not sure how to do so with the installer script and this particular printer.

**Comment by grrminator** [comment]
Sorry to bug. But was this addressed?

**Comment by DaMan9K** [comment]
Hi,In general, you can change the value of the parameter in KAMP_setting.cfg
parameter: variable_purge_margin is in fact a purge line and what difference does it make how far it is from the calibration area
