### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by lvlacleod** [Guilouz/Creality-K1-and-K1-Max#101]
### What happened?

Backup creates a file backup_config.tar but within it is 1 file called backup_config which is 77.5KB

### What did you expect to happen instead?

I expected it to back up all klipper files and KAMP files and add then to the tar file

### How to reproduce this issue?

Just run backup from the installer menu

**Comment by Guilouz** [comment]
Backup is working fine. Make sure your root folder is not full.

**Comment by lvlacleod** [comment]
Root folder is empty
![backup](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/51907297/6b184f39-b7ab-4efb-9478-2d353c821ad0)

This is what is in the tar file

**Comment by Guilouz** [comment]
That's mean your root folder is full. You must restore factory settings.

**Comment by lvlacleod** [comment]
Unless I am missing something obvious this is not full
![Untitled-1](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/51907297/cdb0ae10-6d48-4034-b2ef-badbe351283a)

**Comment by Guilouz** [comment]
in SSH enter this command : df -H

And show me the result.

**Comment by lvlacleod** [comment]
wow, no need to show results. size 107M used 107M but here it is anyway.
