### ISSUE TITLE
Kamp error to install

### ISSUE THREAD

**Issue by fionoob** [Guilouz/Creality-K1-and-K1-Max#105]
### What happened?

I'm using firmware 1.3.2.1 and when I try to install KAMP I get the error shown in the image
![Captura de tela 2023-11-11 222056](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/7783769/503f282f-b26a-4e9b-a3e7-929cbce77951)

### What did you expect to happen instead?

I was hoping it would install, I already did this procedure on another printer and everything worked fine.

### How to reproduce this issue?

Just try installing KAMP and wait

**Comment by lvlacleod** [comment]
Update the installer script. You're using an old version
