### ISSUE TITLE
Small error in the Install Official Builds description

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#11]
Hello, thanks in advance for your work and this great wiki! I have already used it many times .-)
I have just discovered that you have added a new script to your repo incl. instructions. Exactly what I was looking for!

There I noticed two small things:

- there is one sh. too much
<img width="1353" alt="Bildschirmfoto 2023-09-15 um 08 41 03" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/3c1fd765-b7f8-46ed-8397-dd29b0fbee22">

You describe that you first copy your script to root to install entware via the script. But to get access to root via sftp I have to install entware first. Maybe I have a mistake in thinking.
I think it should work like this:

To get sftp access i must first:
wget -O -  https://openk1.org/static/entware/install-entware-k1.sh | /bin/sh

and then
opkg install openssh-sftp-server; ln -s /opt/libexec/sftp-server /usr/libexec/sftp-server

only after that I can copy your script to root via the sftp connection and can call the script
creality/installer.sh

I hope you can understand what I mean.

Best regards and again a big thank you!

Edit: Something else comes to mind. You should point out that installer.sh needs permissions to be executed.
Edit 2: Maybe a hint that you should change your root password in the wiki wouldn't be bad either.

**Comment by Guilouz** [comment]
sh it's not an error, it's to give privileges on sh script.

MoboXterm working without SFTP, that was it's not needed to install Entware.
Entware is only for people want to install package.

Yes I will add new functions/information, this is really a first approach.

**Comment by Nastras** [comment]
Ok that was not known to me. I use another SFTP program and there I can only access the folders when I have installed the share with entware. Thanks for the quick feedback.
