### ISSUE TITLE
Backup function for installer.sh

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#12]
Hey it's me again,

tell me, is there a possibility that you extend the script with a backup function? So that all important files like those in printer_data etc. are backed up and packed?

So that you only have to backup this folder to have your complete backup?

Maybe it is also possible to backup this folder directly to mnt/ on a NAS 😅?

I think that would be a great extension for your script 😉

Best regards

**Comment by Guilouz** [comment]
Yes it is in my mind, this script is really a first version at the request of many people.

**Comment by Nastras** [comment]
Great 😘
