### ISSUE TITLE
"screws_tilt_adjust" not implemented? 

### ISSUE THREAD

**Issue by DrFailbucket** [Guilouz/Creality-K1-and-K1-Max#136]
### What happened?

I was trying to add the "screws_tilt_adjust" to the printer.cfg, after Rebooting it reports with this error: `{"code": "key341", "msg": "Section 'screws_tilt_adjust' is not a valid config section\n\nOnce the underlying issue is corrected, use the \"RESTART\"\ncommand to reload the config and restart the host software.\nPrinter is halted\n", "values": ["screws_tilt_adjust"]}`

### What did you expect to happen instead?

That *screws_tilt_adjust* would work as known on my other Printers

### How to reproduce this issue?

Adding `screws_tilt_adjust` to the printer.cfg and hit *Save&Restart*

### Additional information:

Comment from Official Klipper Discord: *Doesnt matter if it's rooted or not it's still creality's version of klipper, and if you get that error message it means they have removed the module that provided that particular section*

**Comment by Guilouz** [comment]
Not related to the wiki. Can’t help you.

**Comment by StofflHD** [comment]
With this you can add the screw_tilt_adjust functionality. SSH into your printer and run these commands:

cd /usr/share/klipper/klippy/extras

wget -O bed_screws.py "https://raw.githubusercontent.com/CrealityOfficial/K1_Series_Klipper/main/klippy/extras/bed_screws.py"

wget -O screws_tilt_adjust.py "https://raw.githubusercontent.com/CrealityOfficial/K1_Series_Klipper/main/klippy/extras/screws_tilt_adjust.py"

**Comment by DrFailbucket** [comment]
Thanks StoffelHD, i'll try it and update when i got some results 👍

**Comment by DrFailbucket** [comment]
> With this you can add the screw_tilt_adjust functionality. SSH into your printer and run these commands:
> 
> cd /usr/share/klipper/klippy/extras
> 
> wget -O bed_screws.py "https://raw.githubusercontent.com/CrealityOfficial/K1_Series_Klipper/main/klippy/extras/bed_screws.py"
> 
> wget -O screws_tilt_adjust.py "https://raw.githubusercontent.com/CrealityOfficial/K1_Series_Klipper/main/klippy/extras/screws_tilt_adjust.py"

THANK YOU!

Worked like a charm!
