### ISSUE TITLE
[BUG] Images referenced from wiki cannot be opened

### ISSUE THREAD

**Issue by mulder999** [Guilouz/Creality-K1-and-K1-Max#138]
### What happened?

Images reference `private-user-images.githubusercontent.com/12702322/...` which is not accessible

### What did you expect to happen instead?

Images should probably reference `https://github.com/Guilouz/Creality-K1-and-K1-Max/blob/main/...` or similar public URL instead

### How to reproduce this issue?

1. Open the wiki (from a private session or after logging out if you don't see immediately the issue)

For testing, the page: `https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Boards-Layout` can be used. But pretty much every other are concerned.

**Comment by Guilouz** [comment]
All pics are now hosted on repo to avoid issue.
