### ISSUE TITLE
[BUG] <No Purgeline on v1.1.2-6-gd4dee4c8>

### ISSUE THREAD

**Issue by Nazgile94** [Guilouz/Creality-K1-and-K1-Max#143]
### What happened?

01:17
{"code":"key61, "msg":"Unknown command:_LINE_PURGE", "values": ["_LINE_PURGE"]}
01:16
{"code":"key61, "msg":"Unknown command:_SMART_PARK", "values": ["_SMART_PARK"]}

### What did you expect to happen instead?

purgeline printed

### How to reproduce this issue?

just updated to new version

### Additional information:

already uninstalled via helper script, updated helperscript and reinstalled kamp - got the erro 01:17
{"code":"key61, "msg":"Unknown command:_LINE_PURGE", "values": ["_LINE_PURGE"]}
01:16
{"code":"key61, "msg":"Unknown command:_SMART_PARK", "values": ["_SMART_PARK"]} 

and he starts print after doing kamp bed mesh.

K1 Max

Mainsail v2.8.0
Moonraker v0.8.0-204-gfb15b2a3
KAMP-for-K1-Series v1.1.2-6-gd4dee4c8

**Comment by Guilouz** [comment]
https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Wiki-Changelog

**Comment by Nazgile94** [comment]
Thanks, fixed 👌🥳
