### ISSUE TITLE
Timelapse In Browser viewer Issue

### ISSUE THREAD

**Issue by hjkeller** [Guilouz/Creality-K1-and-K1-Max#147]
### What happened?

When attempting to view timelapse videos via mainsail in firefox I am met with the following error:
"No video with supported format and MIME type found."
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/14224724/06253320-f5cb-4aac-bd82-f564c8b69200)
When attempting to view via the device tab of orcaslicer I am met with a blank video window.
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/14224724/c658d147-9713-452a-97fc-e6b4e5297eca)

### What did you expect to happen instead?

The expected behavior is that the timelapse clip plays back in the webui or orca slicer device tab.

### How to reproduce this issue?

Attempt to view any video in the timelapse section.

### Additional information:
[config.zip](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13479666/config.zip)

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/14224724/16b40f47-159d-499d-bdac-ef364d6159da)

**Comment by Guilouz** [comment]
Not related to the wiki. Please post only issue related to the wiki.

**Comment by hjkeller** [comment]
> Not related to the wiki. Please post only issue related to the wiki.

Please advise the appropriate location to post. Is this something you support or should I go to moonraker/timelapse directly?

**Comment by Guilouz** [comment]
Camera working on another web browser?

**Comment by hjkeller** [comment]
> Camera working on another web browser?

The camera works and the timelapase videos can be downloaded and viewed in VLC. Just not in the browser/slicer timelapse pane.

**Comment by Guilouz** [comment]
Working fine with Fluidd. Maybe an issue with your browser or with Mainsail.

**Comment by ASCONTRACT1** [comment]
> This is what happened in Fluidd: ![image](https://private-user-images.githubusercontent.com/14224724/286037637-1f3da667-8f1d-47a3-beda-f254b4f7d45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzOTczMzIsIm5iZiI6MTcwMzM5NzAzMiwicGF0aCI6Ii8xNDIyNDcyNC8yODYwMzc2MzctMWYzZGE2NjctOGYxZC00N2EzLWJlZGEtZjI1NGI0ZjdkNDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDA1NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzlkNTZjMGEzODQ4MTczNzZlZmFmNTVlMWE0OGRhNGQ2ZjRjYzcyNjI5YjE3OThhZGRjOWJhZjY0YTc4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLPbDOeesI4YelSgl3pIfbx9kPA9xOndAaODhdUrCEk) Happens on firefox, mobile firefox, and chromium based browsers in fluidd or mainsail. This has happened after factory installs also. Any other thoughts or suggestions on where I might check?

Did you ever figure this out im running into the same issue where it doesnt play in browser or orca and after download gives .mp4v codecs error. My sonic pad klipper instance doesn’t have this issue with timelapse so it would be nice to fix this.

**Comment by hjkeller** [comment]
> > This is what happened in Fluidd: ![image](https://private-user-images.githubusercontent.com/14224724/286037637-1f3da667-8f1d-47a3-beda-f254b4f7d45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzOTczMzIsIm5iZiI6MTcwMzM5NzAzMiwicGF0aCI6Ii8xNDIyNDcyNC8yODYwMzc2MzctMWYzZGE2NjctOGYxZC00N2EzLWJlZGEtZjI1NGI0ZjdkNDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDA1NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzlkNTZjMGEzODQ4MTczNzZlZmFmNTVlMWE0OGRhNGQ2ZjRjYzcyNjI5YjE3OThhZGRjOWJhZjY0YTc4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLPbDOeesI4YelSgl3pIfbx9kPA9xOndAaODhdUrCEk) Happens on firefox, mobile firefox, and chromium based browsers in fluidd or mainsail. This has happened after factory installs also. Any other thoughts or suggestions on where I might check?
> 
> Did you ever figure this out im running into the same issue where it doesnt play in browser or orca and after download gives .mp4v codecs error. My sonic pad klipper instance doesn’t have this issue with timelapse so it would be nice to fix this.

Regrettably I have not. I even did a full factory reset and couldn't get it to work.
