### ISSUE TITLE
Configuration Mobilereaker

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#15]
I need help again. I am in the process of testing Mobilereaker. I have installed the companion with the script and downloaded the app from the iOS appstore. Now it hangs when setting up in the app. I can't find good documentation either.
When I select simple and under printer address enter the ip of the printer 192.168.178.140 or 192.168.178.140:4409 I get an error on test connection.

An API key for Moonraker do I need this?

I hope I am on the right track?

![tempImageT7D3rn](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/dd326131-dc12-412a-80a3-c09e1103b729)
![tempImagexoG9F2](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/ecc690c3-4c23-4654-a5fc-ced47ee43dc5)

**Comment by Guilouz** [comment]
There is issue in simple mode, you must configure it in advanced mode.

**Comment by Nastras** [comment]
Ohhh man, I couldn't have known that. I have now selected the advanced mode and here also nothing works I think it is because of my settings. Do you have a tip again? 🥹

![Bildschirmfoto 2023-09-16 um 17 27 36](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/c3a70882-4dee-444d-8f8c-f6a21daf1c0e)
![Bildschirmfoto 2023-09-16 um 17 28 21](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/364bfde9-ad99-409f-9d3d-f38f05d39252)

**Comment by Guilouz** [comment]
You have missed port in your ip and websocket.

**Comment by Nastras** [comment]
Now I was able to establish a connection. Thanks for the hint. I had always tried with port but did not enter it at wegsacket.
A small error I still have with the cam and do not know exactly what mobileraker wants here?

![IMG_0107](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/4966df7f-42f4-464e-9eb4-817ccb983453)

**Comment by Nastras** [comment]
I found this but I am not sure if it is the same error. I have reported this error there in the issue. Is the camera working for you?

https://github.com/Clon1998/mobileraker/issues/203

**Comment by Guilouz** [comment]
Yes with this settings:

![IMG_1257](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/7691ed89-4c35-4e1e-85f1-98084bf7b8df)
![IMG_1258](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/448c2c44-6072-46cc-b9ee-77f5401b34d5)

**Comment by Nastras** [comment]
I can not select the camera function in the iOS app, I'll install the app again and set up again to see if it works. I will report.

**Comment by Nastras** [comment]
The camera stream is now displayed. I had to rename the camera to Mainsail for this. I had a space in the name and mobileraker did not like it. Thanks for the support 💪
