### ISSUE TITLE
Klipper Git Repo Detached

### ISSUE THREAD

**Issue by momonator25** [Guilouz/Creality-K1-and-K1-Max#151]
### What happened?

I followed the install guide after unlocked root accsess with the newest firmware (1.3.2.20) from creality  with the helper script. Everything seems to work but the Klipper Repo is detached from Git.

### What did you expect to happen instead?

Update is possible via the _Update Manager_ as described [here](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Update-Manager)
![klipper_git_detached_k1](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/67191477/e4ceb293-d8e1-48c9-8bb9-e9dda5d86e3c)

### How to reproduce this issue?

- Install newest firmware (1.3.2.20)
- Install Mainsail via Helper Script
- Go to Mainsail Web Frontend
- Go to Machine

**Comment by momonator25** [comment]
no if have not, should I?

**Comment by Guilouz** [comment]
Yes… It’s indicated on the wiki.

**Comment by momonator25** [comment]
Oh ok my bad. It's because I have installed the rooted firmware OTA not with this guide. I guess we can close this. Sorry and thanks for the fast reply!
