### ISSUE TITLE
[BUG] cpu temp

### ISSUE THREAD

**Issue by julwarrior** [Guilouz/Creality-K1-and-K1-Max#152]
### What happened?

How can we display the CPU Temp instead of the MCU Temp, because the temperature between the CPU fan and the temperature of the MCU does not match.
thanks 

Comment peut-on afficher le cpu temp en lieu et place du mcu temp , car les temperature entre le cpu fan et la temperature du mcu ne corresponde pas .
à l'avance merci .

### What did you expect to happen instead?

Most users have the MCU Temp displayed on FluidD and Mainsail, and on your screens you can see the CPU Temp

la plupart des utilisateurs ont le mcu temp affiché sur fluidd et mainsail , et sur vos screens on voit bien le cpu temp .

### How to reproduce this issue?

![286217301-07260fbf-d298-468c-afde-94549b421f5d](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/152225894/2b121d8a-0b13-4f46-a78c-1224ca46b508)

### Additional information:

![286217333-f5a0b17d-d286-479d-b517-0e25812dc42a](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/152225894/997fc974-180d-4033-8357-9130876d0b83)

**Comment by Guilouz** [comment]
MCU ou CPU c’est la même chose. J’ai juste changé le nom.

A l’avenir merci d’éviter reporter un problème qui n’en est pas un via PR, il y a un forum de discussion pour cela.
