### ISSUE TITLE
[BUG] PR_ERR_CODE_G28_Z_DETECTION_TIMEOUT: G28 Z try probe out of times.

### ISSUE THREAD

**Issue by jeanfbrito** [Guilouz/Creality-K1-and-K1-Max#154]
### What happened?

Dont know why today when starting a new print this shows up I send the gcode from Orca and then I need to make it restart the print from Fluidd so it works normally.
```
22:27:50 // [RAISE_ERROR]{'code': 'key529', 'msg': 'PR_ERR_CODE_G28_Z_DETECTION_TIMEOUT: G28 Z try probe out of times.', 'values': []}
22:27:50 !! {'code': 'key529', 'msg': 'PR_ERR_CODE_G28_Z_DETECTION_TIMEOUT: G28 Z try probe out of times.', 'values': []}
22:27:50 !! {'code': 'key529', 'msg': 'PR_ERR_CODE_G28_Z_DETECTION_TIMEOUT: G28 Z try probe out of times.', 'values': []}
22:27:50 !! {'code': 'key529', 'msg': 'PR_ERR_CODE_G28_Z_DETECTION_TIMEOUT: G28 Z try probe out of times.', 'values': []}
```
I'm using Orca 1.8.0 since it release and firmware 1.3.2.20 since it came public from OTA.
Nothing changed to this start to happen today.
I'm using KAMP all the time.

Any idea from where it comes? This new firmware makes a very weird movement on Z when it will home, dont know if this can make something loose and give the problem.

### What did you expect to happen instead?

No errors as two days before.

### How to reproduce this issue?

Send a gcode from Orca.

**Comment by Guilouz** [comment]
Not related to the wiki, it seems an Prtouch issue. Make sure to do a factory reset after updating firmware.

Please only post issue related to the Wiki.
