### ISSUE TITLE
 INPUT_SHAPER macro - ERROR

### ISSUE THREAD

**Issue by nickboul** [Guilouz/Creality-K1-and-K1-Max#155]
### What happened?

{"code":"key165", "msg": "Error evaluating 'gcode_macro INPUT_SHAPER:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'axis_maxumum' ", "values": ["gcode_macro INPUT_SHAPER:gcode", "jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'axis_maxumum' "]}

### What did you expect to happen instead?

Start the manual input shaping

### How to reproduce this issue?

every time i press the macro shortcut

**Comment by nickboul** [comment]
It's on an K1 max on the latest firmware. 

I have attached the printer.cfg and gcode_macro.cfg and the log.

Thank you.

I
[klippy.log.2023-11-27.txt](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13513380/klippy.log.2023-11-27.txt)


[printer.txt](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13513346/printer.txt)
[gcode_macro.txt](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13513347/gcode_macro.txt)

**Comment by nickboul** [comment]
And do the procedure again from the beginning?

**Comment by nickboul** [comment]
ok thank you!

**Comment by winbard** [comment]
Hello,

first THANK YOU very much for this work for the K1max Guilouz.

I have the same problem with the macro INPUT_SHAPER
at the end comes this
15:25:27 
// Shaper calibration data written to /tmp/calibration_data_y_20231201_151638.csv file
15:25:28 
// The SAVE_CONFIG command will update the printer config file
// with these parameters and restart the printer.
15:25:28 
// Klipper state: Shutdown
15:25:28 
!! {"code":"key60", "msg":"Internal error on command:M84", "values": ["M84"]}
15:25:29 
!! {"code":"key60", "msg":"Internal error on command:INPUT_SHAPER", "values": ["INPUT_SHAPER"]}

The macro INPUTSHAPER works

Best regards
Klaus

**Comment by Guilouz** [comment]
Just remove M84 command in INPUT_SHAPER macro

**Comment by winbard** [comment]
Thanks for help.
Now i get no fault but it came this
{"code":"key1", "msg":"Exception in flush_handler
Once the underlying issue is corrected, use the
'FIRMWARE_RESTART' command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
"}

**Comment by Guilouz** [comment]
Your issue is on your machine, i use this macro without issue
