### ISSUE TITLE
Feature request for Klipper-Adaptive-Meshing-Purging in install.sh

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#16]
Wouldn't that also be a great extension in the future for your install script? 
I hope this will not be too much 😅

https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging

**Comment by Guilouz** [comment]
Already done in my latest script v1.3

**Comment by Nastras** [comment]
Ohhh man you are really good 😁
Any custom stuff need to be done after installation?

Ps. I still have something would not like to open another issue 😁. The timelapse function could perhaps also be included?
https://github.com/mikebcbc/creality-k1-moonraker-timelapse
