### ISSUE TITLE
[Fan Control] <Not actually controlling the CPU/MCU Fan>

### ISSUE THREAD

**Issue by kyesniper** [Guilouz/Creality-K1-and-K1-Max#161]
### What happened?

I've followed the instructions posted in the fan control section and made the necessary updates to the config and macro files, I can see the CPU fan, Chamber fan controls and reporting in the temp/fan areas. I noticed after a print was finished and the machine was left Idle (K1 Max) for several hours, the MCU was reporting 65c, the fan was reporting 100% but when I put my hand under the fan itself on the machine, it wasn't spinning at all. Setting the hotend to 50c turned the fan on as usual, when it cooled below 40c the fan shut off again.

### What did you expect to happen instead?

CPU/MCU Fans to be automatically controlled based on temperature of the CPU/MCU on the motherboard, not controlled by the hotend fan.

### How to reproduce this issue?

I'm not sure if I'm the only one who's experienced this issue but I assume something is either wrong with the setup, or my config somewhere which should replicate the issue for others.

### Additional information:

![K1 Max Overheating](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/99146339/e8b303c0-4568-4fea-967e-dd4f918854a4)

Printer.cfg is as follows:

# K1-MAX
# Printer_size: 300x300x300
# Version: v1.0.28
# CreateDate: 2023/03/21
# Nozzle_mcu: chip: GD32F303CBT6
#             version: K1-NOZZLE-M_V12
# Leveling_mcu: chip: GD32E230F8P6
#             version: K1-MAX-L-V11
# mcu: chip: GD32F303RET6
#      version: CR4CU220812S12

[include sensorless.cfg]
[include gcode_macro.cfg]
[include printer_params.cfg]
[include KAMP_Settings.cfg]
[include ./KAMP/Adaptive_Meshing.cfg]       # Include to enable adaptive meshing configuration.
#[include ./KAMP/Line_Purge.cfg]             # Include to enable adaptive line purging configuration.
[include camera-settings.cfg]
[exclude_object]
[include extra_macro.cfg]

[mcu]
serial: /dev/ttyS7
baud: 230400
restart_method: command

[mcu nozzle_mcu]
serial: /dev/ttyS1
baud: 230400
restart_method: command

[mcu leveling_mcu]
serial: /dev/ttyS9
baud: 230400
restart_method: command

[verify_heater extruder]
[verify_heater heater_bed]
check_gain_time: 120
heating_gain: 1.0
hysteresis: 10

[mcu rpi]
serial: /tmp/klipper_host_mcu

[bl24c16f]
i2c_mcu: rpi
i2c_bus: i2c.2
i2c_speed: 400000

[idle_timeout]
timeout: 99999999

[virtual_sdcard]
path: /usr/data/printer_data/gcodes

[gcode_arcs]
resolution: 1.0

[temperature_sensor mcu_temp]
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100

[temperature_sensor chamber_temp]
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC5
min_temp: 0
max_temp: 125

[stepper_x]
step_pin: PC2
dir_pin: !PB9
enable_pin: !PC3
microsteps: 32
rotation_distance: 72
endstop_pin: tmc2209_stepper_x:virtual_endstop
position_endstop: 306.5
position_min: -2
position_max: 306.5
homing_speed: 36
homing_retract_dist:0

[tmc2209 stepper_x]
uart_pin:PA9
interpolate: True
run_current:1.5
hold_current:1.0
sense_resistor: 0.100
stealthchop_threshold: 0
uart_address:3
diag_pin: ^PB12
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 1
# driver_TOFF: 1
# driver_HEND: 0
# driver_HSTRT: 7
driver_SGTHRS: 65

[stepper_y]
step_pin: PB8
dir_pin: !PB7
enable_pin: !PC3
microsteps: 32
rotation_distance: 72
endstop_pin: tmc2209_stepper_y:virtual_endstop
position_endstop: -2
position_min: -2
position_max: 306
homing_speed: 36
homing_retract_dist:0

[tmc2209 stepper_y]
uart_pin:PA10
interpolate: True
run_current:1.5
hold_current:1.0
sense_resistor: 0.100
stealthchop_threshold: 0
uart_address:3
diag_pin: ^PB13
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 1
# driver_TOFF: 1
# driver_HEND: 0
# driver_HSTRT: 7
driver_SGTHRS: 65

[stepper_z]
step_pin: PB6
dir_pin: !PB5
enable_pin: !PC3
microsteps: 16
rotation_distance:8
gear_ratio: 64:20
endstop_pin: tmc2209_stepper_z:virtual_endstop# PA15   #probe:z_virtual_endstop
position_endstop: 0
position_max: 305
position_min: -10
homing_speed: 10
second_homing_speed: 1
homing_retract_dist: 2.0

[tmc2209 stepper_z]
uart_pin: PA11
uart_address: 3
run_current: 0.8
diag_pin: ^PB14
stealthchop_threshold: 0
sense_resistor: 0.100
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 1
# driver_TOFF: 1
# driver_HEND: 2
# driver_HSTRT: 2
driver_SGTHRS: 0

[extruder]
max_extrude_only_distance: 1000.0
max_extrude_cross_section: 80
step_pin: nozzle_mcu:PB1
dir_pin: nozzle_mcu:PB0
enable_pin: !nozzle_mcu:PB2
microsteps: 16
rotation_distance: 6.9
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: nozzle_mcu:PB7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: nozzle_mcu:PA0
pressure_advance: 0.04
pressure_advance_smooth_time: 0.040
control: pid
pid_Kp: 25.013
pid_Ki: 2.566
pid_Kd: 60.966
min_temp: 0
max_temp: 320

[tmc2209 extruder]
uart_pin: nozzle_mcu:PB11
tx_pin: nozzle_mcu:PB10
uart_address: 3
run_current: 0.55
sense_resistor: 0.150
stealthchop_threshold: 0
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 2
# driver_TOFF: 3
# driver_HEND: 0
# driver_HSTRT: 5

[heater_bed]
heater_pin: PC8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC4
control: pid
pid_Kp: 37
pid_Ki: 0.18
pid_Kd: 280
min_temp: 0
max_temp: 125

[filament_switch_sensor filament_sensor]
pause_on_runout: true
switch_pin: !PC15
runout_gcode:
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G91
    G0 E30 F600
    G90
  {% endif %}

[filament_switch_sensor filament_sensor_2]
pause_on_runout: true
switch_pin: !nozzle_mcu:PA10

[multi_pin heater_fans]
pins:nozzle_mcu:PB5,PB2

[heater_fan hotend_fan]
pin: multi_pin:heater_fans
heater: extruder
heater_temp: 40

[static_digital_output my_fan_output_pins]
pins: nozzle_mcu: PB6

[output_pin fan0]
pin: !nozzle_mcu: PB8
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin fan1]
pin: PC0
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin fan2]
pin: PB1
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin LED]
pin:PB0
pwm: True
cycle_time: 0.010
value: 1

[output_pin power]
pin: PC9

[adxl345]
cs_pin: nozzle_mcu:PA4
spi_speed: 5000000
axes_map: x,-z,y
spi_software_sclk_pin: nozzle_mcu:PA5
spi_software_mosi_pin: nozzle_mcu:PA7
spi_software_miso_pin: nozzle_mcu:PA6

[resonance_tester]
accel_chip: adxl345
accel_per_hz: 75
# min_freq: 30
# max_freq: 100
probe_points:
   150,150,10

[prtouch_v2]
pr_version: 2
step_base: 2
z_offset: 0       
noz_ex_com: 0.09 #0.09   喷头加热补偿值
tilt_corr_dis:0.05 # //0.05      #热床差补偿值 
tri_min_hold: 6000,10000 #2000,10000
tri_max_hold: 13000,60000
pres_cnt: 4
pres0_clk_pins: leveling_mcu:PA7
pres0_sdo_pins: leveling_mcu:PA4
pres1_clk_pins: leveling_mcu:PA6
pres1_sdo_pins: leveling_mcu:PA3
pres2_clk_pins: leveling_mcu:PA2
pres2_sdo_pins: leveling_mcu:PA0
pres3_clk_pins: leveling_mcu:PA5
pres3_sdo_pins: leveling_mcu:PA1
show_msg: False
step_swap_pin: PC10
pres_swap_pin: leveling_mcu:PB1
g28_wait_cool_down: true
pa_clr_down_mm: -0.15
clr_noz_start_x: 130
clr_noz_start_y: 303
clr_noz_len_x: 40
clr_noz_len_y: 2
speeds: 2.5,1.0
tri_hftr_cut: 2,1
tri_lftr_k1: 0.50,0.15

#tri_wave_ip:172.22.40.244

#进入调平状态用到的参数
tri_min_hold_1:6000,10000
tri_min_hold_2:6000,10000
tri_min_hold_3:6000,10000
tri_min_hold_4:6000,10000
tri_min_hold_5:6000,10000
tri_min_hold_6:6000,10000

tri_min_hold_7:6000,10000
tri_min_hold_8:6000,10000
tri_min_hold_9:6000,10000
tri_min_hold_10:6000,10000
tri_min_hold_11:6000,10000
tri_min_hold_12:6000,10000

tri_min_hold_13:6000,10000
tri_min_hold_14:6000,10000
tri_min_hold_15:6000,10000
tri_min_hold_16:6000,10000
tri_min_hold_17:6000,10000
tri_min_hold_18:6000,10000

tri_min_hold_19:6000,10000
tri_min_hold_20:6000,10000
tri_min_hold_21:6000,10000
tri_min_hold_22:6000,10000
tri_min_hold_23:6000,10000
tri_min_hold_24:6000,10000

tri_min_hold_25:6000,10000
tri_min_hold_26:6000,10000
tri_min_hold_27:6000,10000
tri_min_hold_28:6000,10000
tri_min_hold_29:6000,10000
tri_min_hold_30:6000,10000

tri_min_hold_31:6000,10000
tri_min_hold_32:6000,10000
tri_min_hold_33:6000,10000
tri_min_hold_34:6000,10000
tri_min_hold_35:6000,10000
tri_min_hold_36:6000,10000

tri_max_hold_1:13000,60000
tri_max_hold_2:13000,60000
tri_max_hold_3:13000,60000
tri_max_hold_4:13000,60000
tri_max_hold_5:13000,60000
tri_max_hold_6:13000,60000
tri_max_hold_7:13000,60000
tri_max_hold_8:13000,60000
tri_max_hold_9:13000,60000
tri_max_hold_10:13000,60000
tri_max_hold_11:13000,60000
tri_max_hold_12:13000,60000
tri_max_hold_13:13000,60000
tri_max_hold_14:13000,60000
tri_max_hold_15:13000,60000
tri_max_hold_16:13000,60000
tri_max_hold_17:13000,60000
tri_max_hold_18:13000,60000
tri_max_hold_19:13000,60000
tri_max_hold_20:13000,60000
tri_max_hold_21:13000,60000
tri_max_hold_22:13000,60000
tri_max_hold_23:13000,60000
tri_max_hold_24:13000,60000
tri_max_hold_25:13000,60000
tri_max_hold_26:13000,60000
tri_max_hold_27:13000,60000
tri_max_hold_28:13000,60000
tri_max_hold_29:13000,60000
tri_max_hold_30:13000,60000
tri_max_hold_31:13000,60000
tri_max_hold_32:13000,60000
tri_max_hold_33:13000,60000
tri_max_hold_34:13000,60000
tri_max_hold_35:13000,60000
tri_max_hold_36:13000,60000

[bed_mesh]
speed: 150
mesh_min: 5,5
mesh_max: 295,295
probe_count: 6,6
fade_start: 5.0
fade_end: 50.0
algorithm: bicubic
bicubic_tension: 0.1

[display_status]

[printer]
kinematics: corexy
max_velocity: 800
max_accel: 20000
max_accel_to_decel: 20000
max_z_velocity: 20
square_corner_velocity: 5.0
square_corner_max_velocity: 200.0
max_z_accel: 300

[pause_resume]
# recover_velocity: 500.

#Testing
[duplicate_pin_override]
pins: PC0, PC5, PB2, ADC_TEMPERATURE

[temperature_fan chamber_fan]
pin: PC0
cycle_time: 0.0100
hardware_pwm: false
max_power: 1
shutdown_speed: 0
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC5
min_temp: 0
max_temp: 70
control: watermark
max_delta: 2
target_temp: 35.0
max_speed: 1.0
min_speed: 0.0

[temperature_fan cpu_fan]
pin: PB2
cycle_time: 0.0100
hardware_pwm: false
max_power: 1
shutdown_speed: 0
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100
control: watermark
max_delta: 2
target_temp: 50.0
max_speed: 1.0
min_speed: 0.0

[output_pin cpu_fan]
pin: PB2
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0
#Testing

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [input_shaper]
#*# shaper_type_x = zv
#*# shaper_freq_x = 35.2
#*# shaper_type_y = zv
#*# shaper_freq_y = 37.8
#*#
#*# [prtouch default]
#*# version = 307
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	  0.122616, 0.142062, 0.150386, 0.228531
#*# 	  0.074140, 0.107873, 0.132961, 0.236984
#*# 	  0.041572, 0.081705, 0.124342, 0.172780
#*# 	  0.025121, 0.071232, 0.150732, 0.182482
#*# x_count = 4
#*# y_count = 4
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.1
#*# min_x = 86.0
#*# max_x = 213.98
#*# min_y = 104.08
#*# max_y = 195.91

**Comment by Guilouz** [comment]
After print it's creality OS it control mcu fan. In fact it enable it when print start and disable it after print end. This can't be controled.
