### ISSUE TITLE
[BUG] KAMP not using mesh

### ISSUE THREAD

**Issue by Pokeylooted** [Guilouz/Creality-K1-and-K1-Max#165]
### What happened?

Im getting this warning/error in console: `No objects detected! Check your gcode and make sure that EXCLUDE_OBJECT_DEFINE is happening before BED_MESH_CALIBRATE is called. Defaulting to regular meshing.
`

### What did you expect to happen instead?

I expected it to not have that warning

### How to reproduce this issue?

Do the KAMP installation, then, start a prin.

**Comment by TrainAss** [comment]
What does your start print macro look like? If you have  'Bed Mesh Clear' referenced in your start print macro after 'exclude object define', that is part of the issue. You need to clear the bed mesh BEFORE exclude object define is called, otherwise you'll clear what was just defined. In addition to that, 'exclude objects' need to be checked under 'others' in the processes section.

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12475579/39fee146-69cc-4c38-a847-e9c796a88a65)

**Comment by Pokeylooted** [comment]
<img width="298" alt="image" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/79169880/d772887f-621a-4b68-82ce-c60965513627">

gcode__macro:
```
[gcode_macro START_PRINT]
variable_prepare: 0
gcode:
  WAIT_TEMP_END
  CLEAR_PAUSE
  {% set g28_extruder_temp = printer.custom_macro.g28_ext_temp %}
  {% set bed_temp = printer.custom_macro.default_bed_temp %}
  {% set extruder_temp = printer.custom_macro.default_extruder_temp %}

  {% if 'BED_TEMP' in params|upper and (params.BED_TEMP|float) %}
    {% set bed_temp = params.BED_TEMP %}
  {% endif %}

  {% if 'EXTRUDER_TEMP' in params|upper and (params.EXTRUDER_TEMP|float) %}
    {% set extruder_temp = params.EXTRUDER_TEMP %}
  {% endif %}

  {% if printer['gcode_macro START_PRINT'].prepare|int == 0 %}
    {action_respond_info("not prepare.\n")}
    PRINT_PREPARE_CLEAR
    CX_ROUGH_G28 EXTRUDER_TEMP={extruder_temp} BED_TEMP={bed_temp}
    CX_NOZZLE_CLEAR
    ACCURATE_G28
    BED_MESH_CLEAR
    BED_MESH_CALIBRATE
  {% else %}
    PRINT_PREPARE_CLEAR
  {% endif %}

  SMART_PARK
  M109 S{extruder_temp}
  M190 S{bed_temp}
  LINE_PURGE
```

**Comment by Guilouz** [comment]
It’s not needed to add anything else in start print.

Your error means your gcode have not info about object or you have not enabled enable_object_processing

**Comment by StofflHD** [comment]
It's all mentioned in the wiki:

https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Use-KAMP

**Comment by Pokeylooted** [comment]
> It's all mentioned in the wiki:
> 
> https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Use-KAMP

I know, as I followed it word to word 

```
# Set to 'True' if you use KAMP
enable_object_processing: True

```

**Comment by Pokeylooted** [comment]
> It’s not needed to add anything else in start print.
> 
> Your error means your gcode have not info about object or you have not enabled enable_object_processing

How can I know if it doesnt have info about object?

**Comment by OXOTH1K** [comment]
Same trouble. enable_object_processing: True. Check Exclude object - true. In gcode I have block with "EXCLUDE_OBJECT_DEFINE"

**Comment by StofflHD** [comment]
Do you have [include KAMP_Settings.cfg] in your printer.cfg?

**Comment by OXOTH1K** [comment]
Yes. I was find the problem... In filename.gcode I have section with `EXCLUDE_OBJECT_DEFINE` but I haven't section with `EXCLUDE_OBJECT_START`. I have no idea what to do with that...

**Comment by radekkierner** [comment]
In my case if I start printing from a fluidd KAMP it works fine, however if I start from a printer with the calibration option checked I get the above error, so it looks like it's not an error in the gcode in the file.

**Comment by Ltek** [comment]
> In my case if I start printing from a fluidd KAMP it works fine, however if I start from a printer with the calibration option checked I get the above error, so it looks like it's not an error in the gcode in the file.

What calibration option? Screenshot please. 
The UI doesnt matter. Fluidd and Mainsail are just visual representations / interfaces of Moonraker which is the API engine behind all of them and does all the control/processing.

If KAMP is not working, its something in your config files that are incorrect.

**Comment by hjoungjoo** [comment]
There is no EXCLUDE_OBJECT_START when using simplify3d.
Simple3d does not currently appear to support EXCLUDE_OBJECT.
And we found that BED_MASH is not running in some situations, such as right after the printer turns on.
There is a problem with the calibration being duplicated on the first output right after the printer is booted, but I always want the KAMP operation and I modified it as below to use the entire BED_MESH when there is a problem.

[gcode_macro START_PRINT]
variable_prepare: 0
gcode:
  M117
  WAIT_TEMP_END
  CLEAR_PAUSE
  {% set g28_extruder_temp = printer.custom_macro.g28_ext_temp %}
  {% set bed_temp = printer.custom_macro.default_bed_temp %}
  {% set extruder_temp = printer.custom_macro.default_extruder_temp %}

  {% if 'BED_TEMP' in params|upper and (params.BED_TEMP|float) %}
    {% set bed_temp = params.BED_TEMP %}
  {% endif %}

  {% if 'EXTRUDER_TEMP' in params|upper and (params.EXTRUDER_TEMP|float) %}
    {% set extruder_temp = params.EXTRUDER_TEMP %}
  {% endif %}

  {% if printer['gcode_macro START_PRINT'].prepare|int == 0 %}
    {action_respond_info("not prepare.\n")}
    PRINT_PREPARE_CLEAR
    CX_ROUGH_G28 EXTRUDER_TEMP={extruder_temp} BED_TEMP={bed_temp}
    CX_NOZZLE_CLEAR
    ACCURATE_G28
    {% if printer.exclude_object.objects == [] %}
      CX_PRINT_LEVELING_CALIBRATION
    {% endif %}
  {% else %}
    PRINT_PREPARE_CLEAR
  {% endif %}

  {% if printer.exclude_object.objects == [] %}
    CX_PRINT_DRAW_ONE_LINE
  {% else %}
    {action_respond_info("KAMP BED MASH START.\n")}
    M190 S{bed_temp}
    BED_MESH_CLEAR
    BED_MESH_CALIBRATE
    {action_respond_info("KAMP LINE_PURGE.\n")}
    SMART_PARK
    M109 S{extruder_temp}
    M190 S{bed_temp}
    LINE_PURGE
  {% endif %}

**Comment by hjoungjoo** [comment]
There is no EXCLUDE_OBJECT_START when using simplify3d.
Simple3d does not currently appear to support EXCLUDE_OBJECT.
And we found that BED_MASH is not running in some situations, such as right after the printer turns on.
There is a problem with the calibration being duplicated on the first output right after the printer is booted, but I always want the KAMP operation and I modified it as below to use the entire BED_MESH when there is a problem.

```
[gcode_macro START_PRINT]
variable_prepare: 0
gcode:
  M117
  WAIT_TEMP_END
  CLEAR_PAUSE
  {% set g28_extruder_temp = printer.custom_macro.g28_ext_temp %}
  {% set bed_temp = printer.custom_macro.default_bed_temp %}
  {% set extruder_temp = printer.custom_macro.default_extruder_temp %}

  {% if 'BED_TEMP' in params|upper and (params.BED_TEMP|float) %}
    {% set bed_temp = params.BED_TEMP %}
  {% endif %}

  {% if 'EXTRUDER_TEMP' in params|upper and (params.EXTRUDER_TEMP|float) %}
    {% set extruder_temp = params.EXTRUDER_TEMP %}
  {% endif %}

  {% if printer['gcode_macro START_PRINT'].prepare|int == 0 %}
    {action_respond_info("not prepare.\n")}
    PRINT_PREPARE_CLEAR
    CX_ROUGH_G28 EXTRUDER_TEMP={extruder_temp} BED_TEMP={bed_temp}
    CX_NOZZLE_CLEAR
    ACCURATE_G28
    {% if printer.exclude_object.objects == [] %}
      CX_PRINT_LEVELING_CALIBRATION
    {% endif %}
  {% else %}
    PRINT_PREPARE_CLEAR
  {% endif %}

  {% if printer.exclude_object.objects == [] %}
    CX_PRINT_DRAW_ONE_LINE
  {% else %}
    {action_respond_info("KAMP BED MASH START.\n")}
    M190 S{bed_temp}
    BED_MESH_CLEAR
    BED_MESH_CALIBRATE
    {action_respond_info("KAMP LINE_PURGE.\n")}
    SMART_PARK
    M109 S{extruder_temp}
    M190 S{bed_temp}
    LINE_PURGE
  {% endif %}
```
