### ISSUE TITLE
Klipper Adaptive Meshing & Purging??

### ISSUE THREAD

**Issue by AiramsRT** [Guilouz/Creality-K1-and-K1-Max#17]
I have installed the plugin from the installer, but now I don't know how to make it work. Should I follow any more steps? In the creator's github it indicates adding some lines in monraker.cfg and printer.cfg and that I don't see them in my configuration, Do I have to add them? Because when I send to print it doesn't make any adaptive mesh.

Thanks!

**Comment by Guilouz** [comment]
See my wiki for that.

And please do not open an issue for questions. There is discussions for that.

Use this only for report issue.

**Comment by AiramsRT** [comment]
Sorry, I had opened the wiki but it only showed how to install with the installer, not all the code was there.

**Comment by Guilouz** [comment]
Refresh your page, all is there :)

**Comment by AiramsRT** [comment]
Yesss!!

Thanks!!!
