### ISSUE TITLE
[BUG] Input Shaper config not consistent

### ISSUE THREAD

**Issue by jaegerschnitzel** [Guilouz/Creality-K1-and-K1-Max#172]
### What happened?

On https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Useful-Macros the Input Shaper Macro ends with M84 but on https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Fix-issue-with-Input-Shaper M84 is missing.

### What did you expect to happen instead?

Both configs should be the same.

### How to reproduce this issue?

Just check both Macros

### Additional information:

Please make the config consistent.

**Comment by Guilouz** [comment]
Fixed.
