### ISSUE TITLE
[BUG] START_PRINT vs PRINT_START in the Orcaslicer profile Machine G-Code

### ISSUE THREAD

**Issue by KyleMatheson** [Guilouz/Creality-K1-and-K1-Max#173]
### What happened?

After installing the latest profiles for the K1, I got this error:
`{"code":"key61, "msg":"Unknown command:PRINT_START", "values": ["PRINT_START"]}`
and after finishing:
`{"code":"key61, "msg":"Unknown command:PRINT_END", "values": ["PRINT_END"]}`

The Orcaslicer Machine G-code is:
`M190 S[bed_temperature_initial_layer_single]`
`M109 S[nozzle_temperature_initial_layer]`
`PRINT_START EXTRUDER=[nozzle_temperature_initial_layer] BED=[bed_temperature_initial_layer_single]`

START_PRINT and END_PRINT should be called in the Orcaslicer Machine G-code.  The print started, but it skipped everything in the macro.

### What did you expect to happen instead?

I expected the START_PRINT gcode macro to run. The print started, but it skipped everything in the macro.

### How to reproduce this issue?

Every time until the Machine G-code is edited

**Comment by Guilouz** [comment]
See : https://github.com/Guilouz/Creality-K1-and-K1-Max/discussions/168
