### ISSUE TITLE
timelapse issue

### ISSUE THREAD

**Issue by bhast2** [Guilouz/Creality-K1-and-K1-Max#18]
After setting everything up my timelapses are in black and white and there is weird color artifacts in the video.
any advice on how to fix this? 
thank you.

**Comment by Guilouz** [comment]
Can you try to replace this file in moonraker/moonraker/moonraker/components/ folder to see it's the same

[timelapse.py.zip](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/12662869/timelapse.py.zip)

**Comment by Guilouz** [comment]
Uninstall it and reinstall it,I have updated it and just tested, it's working.
