### ISSUE TITLE
[BUG] Moonraker dependencies out-of-date causing exception when updating through update manager

### ISSUE THREAD

**Issue by caffeineflo** [Guilouz/Creality-K1-and-K1-Max#182]
### What happened?

I've updated moonraker through the built-in update manager to the latest commit. Since moonraker and the python virtualenv are prepackaged in this repo there was a mismatch on the dependencies that moonraker needs to fully run. 
When trying to connect the latest version of OrcaSlicer with Moonraker or either one of the frontends (Mainsail/Fluidd) I received this error:

```
Could not connect to OctoPrint: HTTP 404: {"error": {"code": 404, "message": "Not Found",
"traceback": "Traceback (most recent call last):\n\n File
\"/usr/data/moonraker/moonraker-env/lib/python3.8/site-packages/tornado/web.py\", line 1681, in
_execute\n result = self.prepare()\n\n File \"/usr/data/moonraker/moonraker/moonraker/app.py\", line
1036, in prepare\n raise tornado.web.HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not
Found\n"}}
```

I spent quite a bit of time during the last few days trying to both natively compile all the dependencies moonraker has on my K1 unsucessfully and now tried to both cross compile as well as using the buildroot I found elsewhere to build the python virtualenv up. Unfortunately I haven't been successful with that yet.

### What did you expect to happen instead?

OrcaSlicer -> Moonraker: Connection success

Moonraker Update -> Update dependencies or avoid the update

### How to reproduce this issue?

Update moonraker to the latest commit, then try to connect OrcaSlicer to Moonraker/Fluidd/Mainsail

### Additional information:

Would love to know how you put together the virtualenv in the moonraker.tar - I'm happy to update it and put a PR up if you tell me how that was compiled

**Comment by Guilouz** [comment]
It's the same Moonraker provided by Creality and updated with git difference with command line.

I have latest Moonraker build without issue:

<img width="1210" alt="Capture d’écran 2023-12-09 à 13 44 07" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/47e9088e-1089-44fd-a00f-5930b7150f12">

<img width="1003" alt="Capture d’écran 2023-12-09 à 13 43 51" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/80fb10bf-8492-44e7-9c43-a0b1b8eef483">

**Comment by caffeineflo** [comment]
FWIW, I found the issue and was able after some additional work to compile all the recent dependencies. I'll put up a PR tomorrow to update the files
