### ISSUE TITLE
[BUG] Restore-Factory-Settings link bad in Wiki

### ISSUE THREAD

**Issue by realumhelp** [Guilouz/Creality-K1-and-K1-Max#186]
### What happened?

Under this section the "[Install-Rooted-Firmware](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Install-Rooted-Firmware#installation)" section the "[Reset Factory Settings](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Restore-Factory-Settings)" link is bad:

I'd imagine the link should probably be pointing here: 
https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Reset-Factory-Settings

### What did you expect to happen instead?

I'd imagine the link should probably be pointing here:
https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Reset-Factory-Settings

### How to reproduce this issue?

Under this section the "[Install-Rooted-Firmware](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Install-Rooted-Firmware#installation)" section click the "[Reset Factory Settings](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Restore-Factory-Settings)" link

**Comment by Guilouz** [comment]
Fixed. Thanks.
