### ISSUE TITLE
[BUG] Moonraker is invalid

### ISSUE THREAD

**Issue by matayom** [Guilouz/Creality-K1-and-K1-Max#205]
[klippy (1).log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13733839/klippy.1.log)
[moonraker (1).log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13733840/moonraker.1.log)
### What happened?

Update manager in Fluidd says that moonraker is invalid, and I cannot update it. Not sure if its related but every 10 prints or so my K1 crashes randomly

### What did you expect to happen instead?

Successful update

### How to reproduce this issue?

No idea

### Additional information:

How do i manually update moonraker from terminal?

**Comment by matayom** [comment]
If i try to click "Recover" i get an error: 
`Application moonraker: Attempting Repo Recovery...
Error Recovering moonraker`
and
`Repo has not been verified, clone aborted`

**Comment by Guilouz** [comment]
Try to remove and reinstall it

**Comment by matayom** [comment]
Can i remove and reinstall **only** moonraker with your helper script without messing anything up? Sorry this is my first time using klipper/moonraker/etc

**Comment by hjoungjoo** [comment]
When updated to v1.3.2.20, there is a conflict with the existing installation file.
I had to delete it all with the installation tool and reinstall it from scratch.

**Comment by matayom** [comment]
> When updated to v1.3.2.20, there is a conflict with the existing installation file. I had to delete it all with the installation tool and reinstall it from scratch.

Simply reinstalling fixed it or is the conflict persistent?

**Comment by hjoungjoo** [comment]
> > When updated to v1.3.2.20, there is a conflict with the existing installation file. I had to delete it all with the installation tool and reinstall it from scratch.
> 
> Simply reinstalling fixed it or is the conflict persistent?

Simply reinstalling fixed.

**Comment by jacquesglerner** [comment]
> > > When updated to v1.3.2.20, there is a conflict with the existing installation file. I had to delete it all with the installation tool and reinstall it from scratch.
> > 
> > 
> > Simply reinstalling fixed it or is the conflict persistent?
> 
> Simply reinstalling fixed.

I have done the reinstall but the particular version that is installed ends in 208 and the last one ends in 223. Not a big deal. Just pointing.
