### ISSUE TITLE
[BUG] <title>nozzle cleaning fan control download error

### ISSUE THREAD

**Issue by xZILFx** [Guilouz/Creality-K1-and-K1-Max#208]
### What happened?

was installing nozzle cleaning fan control and got url errors while downloading
![Screenshot 2023-12-22 034638](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/35664453/1d66e7b1-9e9c-4f3e-ab3f-bdfe3c671a10)
![Screenshot 2023-12-22 035007](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/35664453/dd868069-0f6e-4d9b-aa4b-a40943a89db8)

### What did you expect to happen instead?

ive ran this before and was going a fresh install with the V1.3.2.20 firmware. now it wont install

### How to reproduce this issue?

just install the repository

**Comment by Guilouz** [comment]
Fixed. Update script and reinstall it.

I prepare the new script version that's why link was broken
