### ISSUE TITLE
Moonraker has failed plugins

### ISSUE THREAD

**Issue by alenba90** [Guilouz/Creality-K1-and-K1-Max#216]
### What happened?

After the Moonraker update, the following error occurs when booting
![Anmerkung 2023-12-27 202727](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/155016497/da473141-fdbf-457d-ba1b-26f903cf0d94)

### What did you expect to happen instead?

after the update everything should work normally

### How to reproduce this issue?

after reinstalling Moonraker ( I also re-rooted K1 and reinstalled Klipper)  , the same error occurs.

### Additional information:

Moonraker has failed plugins, please check your logs, update your configuration and restart moonraker.
history
Moonraker warnings found.
Component 'history' failed to load with error: 'Cursor' object has no attribute 'getmulti'
Moonraker plugin configuration can be found
[moonraker.log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13781405/moonraker.log)

**Comment by jrezin** [comment]
Same thing happened after trying to update moonraker in the software update. It seems that the problem, at least here, lies with the "pillow==10.0.1" pip package.
maybe it's trying to mess with something outside /usr/data...

**Comment by Rushent08** [comment]
Having the same problem. Only just rooted my K1 Max only to be greeted by this. 
[moonraker (3).log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13782254/moonraker.3.log)

**Comment by Guilouz** [comment]
It's Moonraker issue since recent PR.
