### ISSUE TITLE
Input Shaper not working after update[BUG] <title>

### ISSUE THREAD

**Issue by Myklt8** [Guilouz/Creality-K1-and-K1-Max#219]
### What happened?

Updated to 1.32.31 and updated and reinstalled all modules, however, the input shaper gives an error and shuts the machine down. It also reverts the cfg file to factory settings

### What did you expect to happen instead?

Input shaper to work as it did before

### How to reproduce this issue?

[klippy (2).log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/13788104/klippy.2.log)
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/126296783/5661cd9a-1e10-4c3c-a3ba-c686cf9c740c)

### Additional information:

It also does the same thing when you run input shaper from the touch screen

**Comment by alenba90** [comment]
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/155016497/67410523-8028-4ce3-8442-27881d76657e)

**Comment by alenba90** [comment]
missing in [gcode_macro Qmode] following cod:

`variable_max_accel: 2500
variable_max_accel_to_decel: 2500`

INPUT_SHAPER works after inserting code

**Comment by Guilouz** [comment]
@alenba90 after fw update you must restore default settings to have latest config files.
There is some changes in latest firmware

**Comment by Myklt8** [comment]
I did a factory reset and reloaded everything, the error went away, but the machine shuts off when doing the inputshaping...when it switches to the Y axis. mcu rpi shut down and rescheduled timer in the past

**Comment by iosub** [comment]
Hi, is  1.32.31 firmware compatible with K1 or K1-max?

**Comment by Myklt8** [comment]
Yes, it supports both

**Comment by VinoY27** [comment]
I too faced the same issue, as said, Update the firmware, reset to factory settings, then follow the steps as per initial setup, root it and then install all the required things as per the Wiki.
