### ISSUE TITLE
[BUG] How to change the position of the purge line?

### ISSUE THREAD

**Issue by gfBarreto** [Guilouz/Creality-K1-and-K1-Max#222]
### What happened?

Purge line being printed on the part.

### What did you expect to happen instead?

I'm using the K1.
Sometimes the purge line remains part of the part.
I traditionally use it on the side on the S1 Pro.
How do I change the location?
Attached I send a piece already printed and another that started printing and I had to stop.
![IMG_20231229_103537834](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/50118176/9dc30b47-3211-405f-9f2d-2f18b84a8020)
![IMG_20231229_103606503_HDR](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/50118176/2838252b-9457-47c9-b0bf-5baad3d82a02)

### How to reproduce this issue?

.

**Comment by Guilouz** [comment]
Not possible without to modify macros code.

Please post issue only for issue. That’s is not an issue.

**Comment by gfBarreto** [comment]
ok, obrigado.

**Comment by Tombraider2006** [comment]
this error occurs when there is no object exception in the slicer. set the flag and there will be no such error.
