### ISSUE TITLE
[BUG] <cannot download fluidd or mainsail>

### ISSUE THREAD

**Issue by thegreat7man** [Guilouz/Creality-K1-and-K1-Max#223]
### What happened?

when i try to install fluidd or mainsail im getting `Downloading Fluidd file...
Connecting to github.com (140.82.121.3:443)
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
 Download failed. Exit code: 1`

### What did you expect to happen instead?

fluidd or mainsail would be installed

### How to reproduce this issue?

go to the help script, install, 2 (fluidd)

**Comment by Guilouz** [comment]
Read the wiki…

**Comment by thegreat7man** [comment]
and solve of the problem with entware is not working

**Comment by thegreat7man** [comment]
```
root@K1-EDE6 /root [#] opkg install wget-ssl
-sh: opkg: not found
```

**Comment by thegreat7man** [comment]
do i need to open new issue ?

**Comment by Guilouz** [comment]
That’s means tou have not installed entware

**Comment by thegreat7man** [comment]
i have installed ` Installing Entware...

Making /opt directory on data partition where there is space, and adding a symbolic link...
Installing Entware using generic installer script...
Connecting to bin.entware.net (158.160.45.54:80)
writing to stdout
Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
-                    100% |********************************|  2760  0:00:00 ETA
written to stdout
Info: Opkg package manager deployment...
Connecting to bin.entware.net (158.160.45.54:80)
wget: can't connect to remote host (158.160.45.54): Connection timed out
chmod: /opt/bin/opkg: No such file or directory
Connecting to bin.entware.net (158.160.45.54:80)
saving to '/opt/etc/opkg.conf'
opkg.conf            100% |********************************|   150  0:00:00 ETA
'/opt/etc/opkg.conf' saved
Info: Basic packages installation...
/bin/sh: /opt/bin/opkg: not found
/bin/sh: /opt/bin/opkg: not found
Info: Congratulations!
Info: If there are no errors above then Entware was successfully initialized.
Info: Add /opt/bin & /opt/sbin to $PATH variable
Info: Add "/opt/etc/init.d/rc.unslung start" to startup script for Entware services to start
Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues
Adding /opt/bin and /opt/sbin to the start of the PATH in the system profile...
Adding startup script...

 Entware has been installed successfully!

 Log out and log back in, and you can now install packages with: opkg install <packagename>`

**Comment by thegreat7man** [comment]
but its going on with this issue

**Comment by thegreat7man** [comment]
maybe there an option to install it from usb localy ? or do i need to change wifi ?

**Comment by thegreat7man** [comment]
oh, and i have updated firmware to 1.3.2.31

**Comment by crackers81** [comment]
Same problem here.

**Comment by thegreat7man** [comment]
please,help me somebody because i cant use printer without it

**Comment by crackers81** [comment]
> please,help me somebody because i cant use printer without it

DO THIS after installing entware
(When it's done, log out of the current SSH session and log in again.)

**Comment by ONealP** [comment]
I keep having the same issue. I log out of current SSH and back in. Same issue. I have reset printer to factory. re-rooted and now cant even install helper installer.

sh: /usr/bin/xauth: not found
root@K1Max-6B13 /root [#] cd && wget --no-check-certificate https://raw.githubusercontent.com/Guilouz/Creality-K1-a
nd-K1-Max/main/Scripts/installer.sh
Connecting to raw.githubusercontent.com (185.199.108.133:443)
wget: got bad TLS record (len:0) while expecting switch to encrypted traffic
wget: error getting response: Connection reset by peer

**Comment by Guilouz** [comment]
That's mean your printer have not the correct date, type this command:

date

and see result

**Comment by ONealP** [comment]
Sorry right after I posted I got called in to work.
typed 
Date and it gave me the correct date and time.

root@K1Max-6B13 /root [#] date
Fri Dec 29 20:50:09 CST 2023

**Comment by thegreat7man** [comment]
im getting this when installing entware `wget: can't connect to remote host (158.160.45.54): Connection timed out`

**Comment by thegreat7man** [comment]
@Guilouz i guess there is the problem even with entware installation

**Comment by Guilouz** [comment]
No entware installation working fine, issue is on your machine or network.

**Comment by thegreat7man** [comment]
@Guilouz i tried few wifi sources and nothing. maybe a new firwmare is bad and i should do downgrade ?

**Comment by thegreat7man** [comment]
this ip is dead

**Comment by Guilouz** [comment]
I use latest fw without issue on my max

**Comment by thegreat7man** [comment]
so what sould i do now? i tried any devices,many wifi's, vpn and nothing. please, help

**Comment by thegreat7man** [comment]
@Guilouz i guess i got the problem. entware's server (158.160.45.54:80) is located in russia and i live in ukraine with are blocking all russian servers. do i have some options to install it in alternative way ?

**Comment by thegreat7man** [comment]
maybe you can make any mirror for it or something else ?

**Comment by Guilouz** [comment]
Have you access to this URL ? http://bin.entware.net/mipselsf-k3.4/installer/

**Comment by thegreat7man** [comment]
yep

**Comment by thegreat7man** [comment]
but cannot with clean ip adress (158.160.45.54:80)

**Comment by thegreat7man** [comment]
maybe there are any mirrors exist ?

**Comment by Guilouz** [comment]
it's the url used in my script and it's the official website.

**Comment by thegreat7man** [comment]
hm... but why it cant connect. previous time i didnt install entware because fluidd installed without it. so maybe i can somehow install it another way ?

**Comment by thegreat7man** [comment]
can i try to use something like mobaxterm and manually install entware ? but for this i need to know wich file and where to place

**Comment by Guilouz** [comment]
You can find the install process here:

https://github.com/Guilouz/Creality-K1-and-K1-Max/blob/054da79a7f9d12a9e3f76bd90607b53dcac401eb/Scripts/installer.sh#L632
