### ISSUE TITLE
[BUG] Entware is not installing in Ukraine

### ISSUE THREAD

**Issue by thegreat7man** [Guilouz/Creality-K1-and-K1-Max#224]
### What happened?

the script cant get access to the entware server because Ukraine has been blocked all Russian servers

### What did you expect to happen instead?

entware could have install

### How to reproduce this issue?

try to install entware from the script in Ukraine

**Comment by Guilouz** [comment]
Please stop open many issue for the same problem.

**Comment by thegreat7man** [comment]
but its the problem and you dont want to even try to help

**Comment by thegreat7man** [comment]
@Guilouz you are ignoring me but at least you can try to help me to somehow solve this. maybe i can somehow install entware manually ?

**Comment by Guilouz** [comment]
I have a life, I'm not always there in front of my github...
Issue is for reporting a github related issue and not for cross country issues...
You've already created an issue for this, so there's no need to create another one!

**Comment by thegreat7man** [comment]
but im not guilty of where i living. i just want to install your awesome script (

**Comment by kisslorand** [comment]
One can always use a VPN...

**Comment by Guilouz** [comment]
I have fixed this with the new script version.

**Comment by thegreat7man** [comment]
oh,thanks a lot ! have a nice day
