### ISSUE TITLE
[BUG] installer script problem

### ISSUE THREAD

**Issue by mindkill666** [Guilouz/Creality-K1-and-K1-Max#228]
### What happened?

When i tried to go to the script in mobaxterm and type: cd && sh ./installer.sh
i get this response : sh: can't open './installer.sh': No such file or directory

### What did you expect to happen instead?

That is would open the script

### How to reproduce this issue?

type in cd && sh ./installer.sh when logged in

**Comment by Guilouz** [comment]
That’s means installer is not present in root folder, you have not downloaded it.

**Comment by mindkill666** [comment]
Ok, i reinstalled it, works again, but i don't know why it got uninstalled, been using it for months.
