### ISSUE TITLE
start_print in kamp not worcking code

### ISSUE THREAD

**Issue by Tombraider2006** [Guilouz/Creality-K1-and-K1-Max#232]
### What happened?

4 days ago you updated the start_print.cfg file in the KAMP assembly, but it is locked in the settings file. 
`#[include ./KAMP/Start_Print.cfg]            # Do not disable this, it's the START_PRINT macro.`

and how to use the start_print if it is duplicated in gcode_macro.cfg 

### What did you expect to happen instead?

I think we need to fix the start_print to print_start name of macro and then everything will work as it should and there’s no need to edit gcode_macro.cfg 
Of course, you need to correct the line in the slicer so that the starting code is taken from the updated file

### How to reproduce this issue?

.

**Comment by Guilouz** [comment]
Change is done for my next script release that will disable automatically stock macro and enable the new one.
