### ISSUE TITLE
[BUG] Fluidd can't be installed

### ISSUE THREAD

**Issue by rendez2k** [Guilouz/Creality-K1-and-K1-Max#234]
### What happened?

Fluidd install fails immediately 

### What did you expect to happen instead?

Fluidd install

### How to reproduce this issue?

Run installer, select 1 then 2

### Additional information:

 Please enter your choice and validate with Enter: 2

 Are you sure you want to install Fluidd ? (y/n): y

 Installing Fluidd...
Downloading Fluidd file...
Connecting to github.com (140.82.121.4:443)
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
Download failed. Exit code: 1

**Comment by Guilouz** [comment]
Please read the wiki…
