### ISSUE TITLE
Bad Gateway 502 - Moonranker (tmp)

### ISSUE THREAD

**Issue by thebayer** [Guilouz/Creality-K1-and-K1-Max#24]
I am facing problems with sending large files through Moonranker on my K1 Max
It fills the tmp partition and gives the Bad Gateway 502 error
![Imagem do WhatsApp de 2023-09-21 à(s) 09 40 47](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12862957/f935e99c-bc96-45d5-9dd0-c7ec53caa57d)
97.4M Sep 21 09:40 moonraker.upload-49100.mru

Then I need to delete the generated file (e.g. moonraker.upload-49100.mru), restart the services and send files smaller than 70mb

**Comment by Guilouz** [comment]
Max upload file size configured in Moonraker is 1024 MiB.

**Comment by thebayer** [comment]
Many thanks for the reply.
but /tmp has a maximum size of 100mb.
when the file is larger than the free space, it gives the Bad Gateway error...
;-(

**Comment by thebayer** [comment]
Many thanks for the reply.
but /tmp has a maximum size of 100mb.
When the file is larger than the free space in /tmp, it gives the Bad Gateway error...
;-(

**Comment by Guilouz** [comment]
Can you send me your gcode file to try when i go home.

**Comment by thebayer** [comment]
Just generate any Gcode larger than 100MB and send it via Moonranker (Orca, Prusa).
Below is the link to a GCode https://we.tl/t-UfrGNBv0TN
this file can be found on Thingverse: https://www.thingiverse.com/thing:4543820

**Comment by Guilouz** [comment]
It's now fixed. Please remove moonraker and reinstall it from my script.

**Comment by thebayer** [comment]
You are THE GUY !!!!!! TKS !!!!!!!!
