### ISSUE TITLE
update_manager mobileraker companion

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#25]
Hello @Guilouz 

I have tried to customize the update manager for mobileraker companion. But I get errors there with this entry. Would it not be useful if the script directly enters the correct update path in monraker.cfg during installation?

[update_manager mobileraker]
type: git_repo
path: ~/mobileraker_companion
origin: https://github.com/Clon1998/mobileraker_companion.git
primary_branch:main
managed_services: mobileraker
virtualenv: ~/mobileraker-env
requirements: scripts/mobileraker-requirements.txt
install_script: scripts/install-mobileraker-companion.sh

https://github.com/Clon1998/mobileraker_companion

![IMG_4931](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/cabab38a-4d6e-415f-abca-598f204becba)

**Comment by joschiv1977** [comment]
For mobileraker_companion there is no real benefit. and if you look into the scripts there are changes for the K1 there are not included into the original repo. So if you use the original mobileraker companion it will break it on your rooted K1.

**Comment by Nastras** [comment]
Thank you for the explanation. I was not aware of that. Then we can close here.
