### ISSUE TITLE
[BUG] Failures installing on 1.3.3.3 firmware with 4.0 installer. 

### ISSUE THREAD

**Issue by jgefaell** [Guilouz/Creality-K1-and-K1-Max#251]
### What happened?

I was overjoyed to see the new firmware this morning and installed it on my Max. I experienced these issues when installing modules. Any idea? The scripts are not in the init.d directory, though I found them elsewhere. Did a link command fail? Thanks, it's likely something I did out of order or a missed step.

When installing KAMP:
```
Restarting services...
no need to update custom config files
old_version: 1029
new_version: 1029
./installer.sh: line 1055: /etc/init.d/S56moonraker_service: not found
./installer.sh: line 1057: /etc/init.d/S56moonraker_service: not found
```

When installing Obico
```
Obico is a Moonraker plugin that allows you to monitor
./installer.sh: line 1782: printf and control your 3D printer from anywhere.: not found

 Are you sure you want to install Obico ? (y/n): 
```
Restarting Moonraker and Nginx services
```
 Do you want to restart Moonraker and Nginx services ? (y/n): y

Restarting services...
./installer.sh: line 3492: /etc/init.d/S50nginx: not found
./installer.sh: line 3493: /etc/init.d/S56moonraker_service: not found
./installer.sh: line 3494: /etc/init.d/S50nginx: not found
./installer.sh: line 3496: /etc/init.d/S56moonraker_service: not found

 Moonraker and Nginx services have been restarted!
```

### What did you expect to happen instead?

Successful completion. 

### How to reproduce this issue?

I'm going to try that later today.

**Comment by Guilouz** [comment]
Not a script issue.

It’s seems you have not moonraker and nginx installed

Have you reset to factory after updating fw?

**Comment by jgefaell** [comment]
PEBCAK
