### ISSUE TITLE
Installation Helper Script

### ISSUE THREAD

**Issue by PhilippeGalid** [Guilouz/Creality-K1-and-K1-Max#256]
### What happened?

When i want to Install Nr 12 Improved Shapers Calibrations nothing happens,everything else works, maybe there is a Script Server Problem, Entware is Installed. But thaks a lot for your hard work. Do you have a solution ? 

### What did you expect to happen instead?

When i click Install - Nr 12 - nothing happens

### How to reproduce this issue?

When i click Install - Nr 12 - nothing happens

### Additional information:

Firmware 1.3.3.3

**Comment by Guilouz** [comment]
No issue with script:

<img width="646" alt="Capture d’écran 2024-01-07 à 18 50 46" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/bf136d57-2821-43a4-9596-a4c0c6e89ade">
