### ISSUE TITLE
Improved Shapers Calibrations

### ISSUE THREAD

**Issue by PhilippeGalid** [Guilouz/Creality-K1-and-K1-Max#259]
### What happened?

Sorry but Install Point 12 Improved Shapers Calibrations Installation doesn't work, when I enter 12 nothing happens, I tried it on two computers, Mac and Windows on the same network, all other installations work. What kind of solution is there? They say there are no errors in the script, so I don't understand why the question doesn't come up whether I want to install it. You are doing a great job, please help, what can I do, Entware is also installed?

### What did you expect to happen instead?

Sorry but Install Point 12 Improved Shapers Calibrations Installation doesn't work, when I enter 12 nothing happens, I tried it on two computers, Mac and Windows on the same network, all other installations work. What kind of solution is there? They say there are no errors in the script, so I don't understand why the question doesn't come up whether I want to install it. You are doing a great job, please help, what can I do, Entware is also installed?

### How to reproduce this issue?

Sorry but Install Point 12 Improved Shapers Calibrations Installation doesn't work, when I enter 12 nothing happens, I tried it on two computers, Mac and Windows on the same network, all other installations work. What kind of solution is there? They say there are no errors in the script, so I don't understand why the question doesn't come up whether I want to install it. You are doing a great job, please help, what can I do, Entware is also installed?

### Additional information:

Sorry but Install Point 12 Improved Shapers Calibrations Installation doesn't work, when I enter 12 nothing happens, I tried it on two computers, Mac and Windows on the same network, all other installations work. What kind of solution is there? They say there are no errors in the script, so I don't understand why the question doesn't come up whether I want to install it. You are doing a great job, please help, what can I do, Entware is also installed?

**Comment by Guilouz** [comment]
As I can said, it's working fine, see:

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/4f8feffe-c841-49a9-b0ed-fb8b53f5457f)

**Comment by NeverUsedID** [comment]
check with "date" if your time is correct.

**Comment by PhilippeGalid** [comment]
Hi thanks for your support i install 5 and after 12 works, thanks for your Support :-)

**Comment by PhilippeGalid** [comment]
Works Now
