### ISSUE TITLE
[BUG] Removing OBICO leads to a ton of errors, lines are not being removed from Config files

### ISSUE THREAD

**Issue by riktanius** [Guilouz/Creality-K1-and-K1-Max#261]
### What happened?

I switched from using OBICO to Octoeverywhere and it seems that when I used the Remove Obico function it did remove all the Obico specific files, but the config files and update manager are now trying to call those files that dont exist anymore. They throw an error. 

### What did you expect to happen instead?

No issues when removing Obico

### How to reproduce this issue?

Install Obico, use it, the use the script to remove Obico

### Additional information:

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/57732530/a07c57c2-3b3d-4268-88cc-a453ba6cdef5)

There was also a major error, but I cleared that by commenting out Obico on any config files I found:

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/57732530/754d5e5c-a10a-41a6-a5bc-ded3414a897a)

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/57732530/11529075-06a0-40fa-9ed9-dd105274372a)

**Comment by Guilouz** [comment]
Obico install and remove is not mine, it's from @kennethjiang.

Can you tell me witch settings are not removed exactly ?

**Comment by kennethjiang** [comment]
@Guilouz Thank you for pinging me for this issue! Didn't realize creality would check `printer.cfg` by line number...

I was originally thinking about putting this line at the bottom of the `printer.cfg`. But Klipper bed level will generate this part at the bottom:

```
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
...
```

Any suggestion on the best way to handle this?

**Comment by Guilouz** [comment]
> @Guilouz Thank you for pinging me for this issue! Didn't realize creality would check `printer.cfg` by line number...
> 
> I was originally thinking about putting this line at the bottom of the `printer.cfg`. But Klipper bed level will generate this part at the bottom:
> 
> ```
> #*# <---------------------- SAVE_CONFIG ---------------------->
> #*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
> ...
> ```
> 
> Any suggestion on the best way to handle this?

For my new script version I add includes after line:

[include printer_params.cfg]

An exemple here:

sed -i '/\[include printer_params\.cfg\]/a \[include Helper-Script/buzzer-support\.cfg\]' /usr/data/printer_data/config/printer.cfg

**Comment by kennethjiang** [comment]
Gotcha! Thank you so much @Guilouz !

**Comment by riktanius** [comment]
According to the Above, I should be able to remove the line from the "printer.cfg" file and everything ok?

Because I tried that and still getting this error:

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/57732530/eead5e75-482f-4c96-ba2e-5a24319a5ffe)

**Comment by riktanius** [comment]
Seems there was a line in Moonraker.conf that I had commented out but needed to just be deleted. Removed the line, restarted, error gone.

**Comment by Guilouz** [comment]
@kennethjiang Did you fix it ?

**Comment by kennethjiang** [comment]
Sorry have been really busy. But will fix it later today.

**Comment by kennethjiang** [comment]
@Guilouz Working on this now. but I realized that `[include printer_params.cfg]` is in `printer.cfg` only when a user has installed using the helper script.

Since the macro file is intended for all moonraker-obico users, including non-K1 users - any idea about a more general approach that works for most or all klipper scenarios??

**Comment by kennethjiang** [comment]
Will the `[printer]` line always be there? if so, I can add in front of that line.

**Comment by kennethjiang** [comment]
I don't like this approach. It looks like `[printer]` usually appears in the middle of the cfg file and hence it's ugly to insert there.

I think a better approach is to insert it before the first `<---------------------- SAVE_CONFIG ---------------------->` line. And if one doesn't exists, insert it at the bottom of the file.

I implemented it here: https://github.com/TheSpaghettiDetective/moonraker-obico/commit/1cab320022f45773395b8a653eb6ffe8d4a21b0f

Not the prettiest code I have written. Feedback/comment welcome! @Guilouz

**Comment by Guilouz** [comment]
@kennethjiang [include printer_params.cfg] is a config file included in K1 config.

Maybe you can add a condition like this to determine if it's K1 OS or not, the K1 and K1 Max run an OS called Buildroot. We detect that by looking at the os-release file.:
```
if grep -Fqs "ID=buildroot" /etc/os-release
```

**Comment by kennethjiang** [comment]
> 
> ```
> if grep -Fqs "ID=buildroot" /etc/os-release
> ```
I'm a little bit afraid that Creality will change this in the future... 

I guess there is no perfectly clean solution here. I'll just go with https://github.com/TheSpaghettiDetective/moonraker-obico/commit/1cab320022f45773395b8a653eb6ffe8d4a21b0f unless you have any objections @Guilouz . Will release it with the next update.

Again I appreciate your help! @Guilouz

**Comment by Guilouz** [comment]
@kennethjiang ok no problem the main thing being that it is no longer at the start of the file.

I take care of removing these includes via my uninstallation script.

**Comment by kennethjiang** [comment]
> @kennethjiang ok no problem the main thing being that it is no longer at the start of the file.
> 
> I take care of removing these includes via my uninstallation script.

Sounds good. Thanks again!

**Comment by Guilouz** [comment]
Fixed with latest script update.
