### ISSUE TITLE
[BUG] Mobileraker plugin not showing installed in app with newest firmware

### ISSUE THREAD

**Issue by riktanius** [Guilouz/Creality-K1-and-K1-Max#264]
### What happened?

Using Mobileraker, after running the script it still doesn't show in the app that the companion is working. Was working before, now not getting notifications. 

### What did you expect to happen instead?

I installed the companion using the script, opened the app, checked the status and shows not installed:

![Screenshot_20240110_124909](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/57732530/bf9cb7b4-57d5-4fa5-bb07-1caf2416ee4c)

### How to reproduce this issue?

Do a full reset of the printer, upgrade the firmware to 1.3.3.3 and then use the script to install the mobileraker companion. Then open the app and check app settings

### Additional information:

Tried reinstalling and it didn't help.

**Comment by Guilouz** [comment]
Can't reproduce issue. Mobileraker notifications works fine with latest firmware 1.3.3.3.

Factory reset must be done after update not before.

<img width="618" alt="Capture d’écran 2024-01-10 à 22 09 01" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/416cdfea-91c4-4c8f-8ee0-5cbe58b7dcaa">

![C7B56041-EA82-40E8-9298-7CCD4C6CEC6A_1_101_o](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/8c5cb635-af96-408b-afa9-1c2828d5549c)

**Comment by riktanius** [comment]
I thought the factory reset would take me back to the original Firmware. I will do the dance again and check back in.
