### ISSUE TITLE
[BUG] Timelapse uses wrong codec

### ISSUE THREAD

**Issue by zellneralex** [Guilouz/Creality-K1-and-K1-Max#265]
### What happened?

See the discussion in https://github.com/mainsail-crew/moonraker-timelapse/issues/141

I would recommend you restore the ffmpeg command and describe the update off ffmpeg as done in https://github.com/mainsail-crew/moonraker-timelapse/issues/141#issuecomment-1886388646

**Please clarify that you modify the original files so that K1 user understand they need to come here to discuss issues**

### What did you expect to happen instead?

Video playable inside the UIs

### How to reproduce this issue?

Do a timelapse

**Comment by iosub** [comment]
Hi

A workaround is to add on the timelapse camera extra options
-vcodec h264   -pix_fmt yuv420p
It works for me

**Comment by bhast2** [comment]
> Hi
> 
> A workaround is to add on the timelapse camera extra options -vcodec h264 -pix_fmt yuv420p It works for me

where do you add this?

**Comment by iosub** [comment]
> > Hi
> > A workaround is to add on the timelapse camera extra options -vcodec h264 -pix_fmt yuv420p It works for me
> 
> where do you add this?
Here
![Captura de pantalla 2024-01-14 030234](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/1330995/c02405f2-3a44-4475-b039-e4c0fbfa1db4)

**Comment by ASCONTRACT1** [comment]
> > > Hi
> > > A workaround is to add on the timelapse camera extra options -vcodec h264 -pix_fmt yuv420p It works for me
> > 
> > 
> > where do you add this?
> > Here
> > ![Captura de pantalla 2024-01-14 030234](https://private-user-images.githubusercontent.com/1330995/296525597-c02405f2-3a44-4475-b039-e4c0fbfa1db4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNTk5NzcsIm5iZiI6MTcwNTI1OTY3NywicGF0aCI6Ii8xMzMwOTk1LzI5NjUyNTU5Ny1jMDI0MDVmMi0zYTQ0LTQ0NzUtYjAzOS1lNGMwZmJmYTFkYjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTkxNDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzExZjA3MTRhOGMxMTBkMjg1MTU3OGE1MTJhMzExNWI5ODVhYjY5Nzc3NjI0ODY4OWVjNDYwYTE4OTRlODkxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.18_WnVbYGZ-Zmmrr3vMjA5QHMD_7TUWhm71iE6QSinw)

Can you do this in fluidd? It would be nice to have it supported just like it is on my sonic pad.

**Comment by Guilouz** [comment]
Fixed. Please update latest script version, remove and reinstall Timelapse.

**Comment by ASCONTRACT1** [comment]
> Fixed. Please update latest script version, remove and reinstall Timelapse.

Hello,
I tried this out by running your latest script and uninstalling and installing moonraker timelapse, but now i dont get a timelapse at the end of a print. Could it be i have some settings wrong because i hit render and it doesnt. Maybe my config is wrong? It includes the helperscript timelapse.cfg and in moonraker i have these lines:
[timelapse]
output_path: /usr/data/printer_data/timelapse/
frame_path: /usr/data/printer_data/frames/
snapshoturl: http://localhost:4408/webcam/?action=snapshot
ffmpeg_binary_path: /usr/bin/ffmpeg
#   Directory where ffmpeg is installed

also it was working before i tried this but i just couldnt view the timelapse in fluid or windows because of the codec

**Comment by Guilouz** [comment]
Use correct moonraker.conf file

**Comment by ASCONTRACT1** [comment]
> Use correct moonraker.conf file

How do i know which is the correct file? Or where do i get the correct config file?

**Comment by Guilouz** [comment]
https://github.com/Guilouz/Creality-K1-and-K1-Max/blob/main/Scripts/files/moonraker/moonraker.conf

**Comment by ASCONTRACT1** [comment]
> https://github.com/Guilouz/Creality-K1-and-K1-Max/blob/main/Scripts/files/moonraker/moonraker.conf

I downloaded the config you linked to, but it doesnt work i got the frames and render to work using my above ffmpeg path and snapshoturl. Its currently stuck rendering with a circle. Does that mean it is working? Its been a few minutes and there is no sign of the final timelapse file. Could there be another issue in another config? I am testing with just 10 frames. Minutes is very long compared to my sonic pad.

**Comment by ASCONTRACT1** [comment]
Ok I played around a bit but now I landed here after updating the moonraker.conf and checking the snapshots were working. I get this error in my log: 
2024-01-26 11:37:54,495 [timelapse.py:render()] - start FFMPEG: /usr/bin/ffmpeg -r 15 -i '/usr/data/printer_data/frames/frame%6d.jpg' -threads 2 -g 5 -crf 23 -vcodec libx264 -pix_fmt yuv420p -preset superfast -an  '/usr/data/printer_data/frames/k1_Cube_PLA_2m58s.gcode_20240126_1137.mp4' -y
2024-01-26 11:37:54,573 [timelapse.py:render()] - Rendering Video failed: /usr/bin/ffmpeg -r 15 -i '/usr/data/printer_data/frames/frame%6d.jpg' -threads 2 -g 5 -crf 23 -vcodec libx264 -pix_fmt yuv420p -preset superfast -an  '/usr/data/printer_data/frames/k1_Cube_PLA_2m58s.gcode_20240126_1137.mp4' -y : Error splitting the argument list: Option not found

**Comment by wKich** [comment]
@ASCONTRACT1 Hi there. I have the same issue. If you run the ffmpeg command from console you will see that K1 has incorrect ffmpeg version, because it says `Unrecognized option 'crf'.`

**Comment by ASCONTRACT1** [comment]
> @ASCONTRACT1 Hi there. I have the same issue. If you run the ffmpeg command from console you will see that K1 has incorrect ffmpeg version, because it says `Unrecognized option 'crf'.`
> 
> Upd. Ok, I got it. You have to install ffmpeg by using `opkg install ffmpeg` and then don't use `/usr/bin/ffmpeg`. The correct one is installed in `/opt/bin/ffmpeg`

OMG this was exactly it! Thank you so much @wKich! You really saved me from the headache of going down the troubleshooting rabbit hole
