### ISSUE TITLE
[BUG] <title> need add to shapers-configs.cfg

### ISSUE THREAD

**Issue by Tombraider2006** [Guilouz/Creality-K1-and-K1-Max#267]
### What happened?

iin first macro have this part

`  {% if printer.toolhead.homed_axes != "xyz" %}
    RESPOND MSG="Homing"
    G28
  {% endif %}`

why not have this part in other macros? this usefull part allows you to run the macro from any position, don’t make mistakes in console.  some like this 

`[gcode_macro BELTS_SHAPER_CALIBRATION]
description: Perform a custom half-axis test to analyze and compare the frequency profiles of individual belts on CoreXY printers
gcode:
  {% if printer.toolhead.homed_axes != "xyz" %}
    RESPOND MSG="Homing"
    G28
  {% endif %}
  {% set min_freq = params.FREQ_START|default(5)|float %}
  {% set max_freq = params.FREQ_END|default(133.33)|float %}
  {% set hz_per_sec = params.HZ_PER_SEC|default(1)|float %}`

### What did you expect to happen instead?

.

### How to reproduce this issue?

.

### Additional information:

.

**Comment by Guilouz** [comment]
Will be added in next version.
