### ISSUE TITLE
Probleme mit Timelapse [BUG] <title>

### ISSUE THREAD

**Issue by Schulli73** [Guilouz/Creality-K1-and-K1-Max#275]
### What happened?

Ich habe folgenden Fehler mit Timelapse: Ich habe Timelapse nach Anweisung vollständig installiert. 
Am PC kann ich die Webcam ganz normal sehen, aber an meinem iPad Pro und IPhone sehe ich nur ein weißes Bild. 
Unter den Einstellungen bei Timelapse kann ich keine Kamera auswählen, um Timelapse vollständig einzurichten. 

Ich habe die neueste Scriptversion 4.2 und die Firmwareversion 1.3.3.3  

### What did you expect to happen instead?

.

### How to reproduce this issue?

.

**Comment by Guilouz** [comment]
In English please.

**Comment by Schulli73** [comment]
> Bitte auf Englisch.

I have the following error with Timelapse: I have fully installed Timelapse as instructed.
I can see the webcam normally on my PC, but on my iPad Pro and iPhone I only see a white image.
Under the Timelapse settings, I cannot select a camera to fully set up Timelapse.

I have the latest script version 4.2 and firmware version 1.3.3.3

**Comment by Guilouz** [comment]
Timelapse is a component to create timelapse of 3D prints.

Your issue have nothing to see with Timelapse but from what I understand it is the display of your webcam which works on PC but not elsewhere, right?

**Comment by Schulli73** [comment]
hallo

As you can see in the first picture here, I see the image from the webcam quite normally on the PC.
![1d](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/e6de4317-816b-4ed1-bcee-0b591086be44)

As you can see in image 2, I cannot select a webcam under the settings on Timelapse to configure it correctly.
![2d](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/84c15926-6e04-4b29-9b81-cddd94642288)

Picture 3 is a screenshot from my iPhone, where I only see a white image when I go to the webcam.
![3d](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/b923fa0d-d51d-4895-9583-4895c70c8bb4)

I hope the pictures help to understand the problem

**Comment by Guilouz** [comment]
So nothing to see with Timelapse you have not image on your phone. It’s not related to wiki issue.
It’s normal tou can’t select camera on maisail it use camera by default.

**Comment by Schulli73** [comment]
But if I add a webcam to the settings myself, I can also see it on my iPhone
![d4](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/f27c93c0-440f-4c63-a281-0b46ff8ae9b8)

**Comment by Schulli73** [comment]
> Mit Timelapse gibt es also nichts zu sehen, was Sie nicht auf Ihrem Handy haben. Es hat nichts mit dem Wiki-Problem zu tun. Es ist normal, dass Sie die Kamera auf dem Maisail nicht auswählen können, es verwendet standardmäßig die Kamera.

 OK, thank you for the information

**Comment by Guilouz** [comment]
Timelapse does not add a camera, it uses the camera already configured.

**Comment by Schulli73** [comment]
> Timelapse fügt keine Kamera hinzu, sondern verwendet die bereits konfigurierte Kamera.

I tried it once

**Comment by Guilouz** [comment]
Is it ok ?

**Comment by Schulli73** [comment]
Hello Guilouz

Yes, the Webcam is working now, great work

**Comment by Schulli73** [comment]
Hello Guilouz

Yes, the webcam is working now, great work

**Comment by Schulli73** [comment]
hello

unfortunately not,
only when I create a web myself

**Comment by Guilouz** [comment]
As I already said Timelapse have nothing to see with webcam display. 

Just try to remove webcam config and re-add webcam.

**Comment by Schulli73** [comment]
Hello, I reset the printer again today and redid everything again. I can see the webcam on the original interface but still not on mainsail

![WhatsApp Bild 2024-01-18 um 07 46 17_98985594](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/7647921d-0a5e-496d-8a1c-6b37cd58f4ce)
![WhatsApp Bild 2024-01-18 um 07 46 16_d8730022](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/f7ce9218-5d55-410e-833d-2bc6b251b273)
![WhatsApp Bild 2024-01-18 um 07 46 17_aecc3986](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/c2c3c474-3bd2-4241-b2ce-816e876f42a1)
![WhatsApp Bild 2024-01-18 um 07 46 16_79d0b9ee](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/145964903/fcf80a73-6ebb-460e-9afb-06c3e239b426)

**Comment by cinealfa** [comment]
I am having the same issue, If I add the camera in moonraker I get a white screen. If change the port from 808 0 to 4409 I get the same white screen.Iff I comment the lines out in moo raker I can set up the camera in the settings but I cannot select it in the timelapse settings. Are you saying that it is not needed because timelapse will default to the only camera available?

**Comment by avxmw** [comment]
I had a similar problem not having a camera view in Orca Slicer, solution/workaround for that was setting `service: mjpegstreamer-adaptive` - maybe that also works here.

**Comment by Biospargel** [comment]
I also can't add the camera to the time lapses in the time lapse option, it is grayed out. otherwise it works in moonraker
![Screenshot 2024-01-23 at 18-19-23 Creality K1](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/68374248/e55e4647-bf4f-4cbe-875c-cdb483f9ea42)

**Comment by Tombraider2006** [comment]
I think I know why all these users are having this problem. here is her solution:

1. go to the helper script and remove  the camera settings item
2. then go to moonraker.cfg and delete the [webcam camera] section. reboot, 
3. add the camera in the settings and then in the timelapse settings. everything will work. 

Now the question is:  why is this so? i don't know but it work.

**Comment by Guilouz** [comment]
Strange issue. I use camera in moonraker.conf without issue.

**Comment by hjkeller** [comment]
I am having a similar issue. at first reboot and before I start a print, the camera works fine. Eventually during a print the camera will stop streaming. Using mainsail or mobileraker companion. Running 1.3.3.5 firmware, freshly reset and installed.

**Comment by jeracom** [comment]
> I am having a similar issue. at first reboot and before I start a print, the camera works fine. Eventually during a print the camera will stop streaming. Using mainsail or mobileraker companion. Running 1.3.3.5 firmware, freshly reset and installed.

I have the same problem!
