### ISSUE TITLE
[BUG] (maybe enhancement) GuppyScreen update not available

### ISSUE THREAD

**Issue by Horgul123** [Guilouz/Creality-K1-and-K1-Max#283]
### What happened?

To update GuppyScreen you just need to run the GuppyScreen Installer again as mentioned in the Guppy Scren instructions. When trying this in the helper script it tells me, that it's already installed.

### What did you expect to happen instead?

Change label to "install/update Guppy Screen" and install it even it it was installed previously

### How to reproduce this issue?

Install Guppy Screen und try to install it again without uninstall first

### Additional information:

n/a

**Comment by Guilouz** [comment]
If you want to update it, you must use GUPPY_UPDATE macro or update it on the screen.

If you want to reinstall completly, you must uninstall it before.

**Comment by Horgul123** [comment]
@Guilouz Ah ok. thanks. Did not know, that there are alternative ways to update as they are not mentioned in the GuppyScreen instructions on Github

**Comment by Guilouz** [comment]
Yes normal, it’s my own addition tu update it from web interface.
