### ISSUE TITLE
[BUG] Section 'gcode_shell_command resonance_graph' is not a valid config section

### ISSUE THREAD

**Issue by Borega** [Guilouz/Creality-K1-and-K1-Max#284]
### What happened?

After install of the improved shapers calibrations I now get the following error:
Section 'gcode_shell_command resonance_graph' is not a valid config section
Klippy.log shows the following:
[ERROR] 2024-01-15 20:04:37,956 [root] [klippy:_connect:201] {"code":"key341", "msg":"Section 'gcode_shell_command resonance_graph' is not a valid config section", "values":["gcode_shell_command resonance_graph"]}
[ERROR] 2024-01-15 20:04:37,959 [root] [klippy:_connect:231] Config error
Traceback (most recent call last):
  File "/usr/share/klipper/klippy/klippy.py", line 193, in _connect
    self._read_config()
  File "/usr/share/klipper/klippy/klippy.py", line 163, in _read_config
    pconfig.check_unused_options(config)
  File "/usr/share/klipper/klippy/configfile.py", line 304, in check_unused_options
    raise error("""{"code":"key341", "msg":"Section '%s' is not a valid config section", "values":["%s"]}""" % (section, section))
configparser.Error: {"code":"key341", "msg":"Section 'gcode_shell_command resonance_graph' is not a valid config section", "values":["gcode_shell_command resonance_graph"]}

Unit is a K1 with 1.3.2.20 firmware.
Removing the improved shapers calibrations removes the error. 
Guppy screen is NOT installed.
### What did you expect to happen instead?

Normal boot behaviour as with all the other installs via the script

### How to reproduce this issue?

install the improved shapers calibrations

**Comment by center-777** [comment]
I have the same problem.
When reinstalling "Klipper Gcode Shell Command", I get the following error

<img width="558" alt="Снимок экрана 2024-01-15 в 15 55 28" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/7359520/ed0c3f41-1990-47ba-9bd8-97c31304be3c">

From "System" menu:
Disk Usage: 1.2G / 6.5G (5.0G available)

**Comment by Borega** [comment]
commenting out the section in shapers-configs.cfg results in the error moving the belts_graph (as I  had expected). Seems to be a reference problem or maybe a problem of missing py packages?

**Comment by Borega** [comment]
The issue was resolved by uninstalling Klipper Gcode Shell Command that I had installed from an old version and installing it anew. Then install input shaper fix and now it works
