### ISSUE TITLE
[BUG] Klipper Adaptive Meshing & Purging mechanical crash

### ISSUE THREAD

**Issue by TheTesla** [Guilouz/Creality-K1-and-K1-Max#289]
### What happened?

If a 360 mm long and 60 mm wide object is fitted 45° diagonally between opposite corners of the print bed, crossing its center on the Creality k1 max, it purges a drop instead of a line in the center of the bed. While printing the first layer, the print head crashes into this drop.

### What did you expect to happen instead?

creating a 45° purge line near the object

### How to reproduce this issue?

print an object with 360 mm by 60 mm footprint, 45° diagonally between two opposite corners

### Additional information:

![IMG_20240117_195157](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/2584345/44042e22-a560-4889-b1d6-fcf45e4a22b6)
![IMG_20240117_200429](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/2584345/9463a56f-91ed-4ce7-8a83-a0e8dce62a31)

**Comment by Guilouz** [comment]
Not possible to do that.
When purge line can’t be done in front of model a purge blob is done on the center and must be removed before start print.

**Comment by itay-grudev** [comment]
Can it be done in a corner or on the back of the build plate?
Is that configurable?
Is the setting in another project?
