### ISSUE TITLE
TLS Error 

### ISSUE THREAD

**Issue by Saberlord** [Guilouz/Creality-K1-and-K1-Max#29]
Currently I am trying to update with the installer, but every wget request made, will always return with a TLS certificate validation error

The running code:

root@creality /root [#] cd && wget https://github.com/Guilouz/Creality-K1-and-K1-Max/raw/main/Scripts/installer.sh
Connecting to github.com (20.205.243.166:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer

It runs through the whole script as well.

**Comment by Guilouz** [comment]
Yes it's normal it's related to OS but there is no issue.

**Comment by Saberlord** [comment]
In that case, how do I avoid getting that error? Change the OS? I used to update with installation script 1.3, but I can't now.

I have also removed Moonraker as I thought that was the issue and now I can't use my printer

**Comment by Saberlord** [comment]
That is the problem, with the TLS error, the SSH cannot get any response from the server so the script cannot pull any files from github.*
![image_2023-09-27_161423011](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/22539700/7327cc83-956e-4ced-a521-8c8d46faa12e)
**

This is what i get when i run the installer script that i transferred into the printer

**Comment by Guilouz** [comment]
Working fine for me :

<img width="936" alt="Capture d’écran 2023-09-27 à 22 39 35" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/6261247c-a857-4ece-b95b-1678f35c48cb">

**Comment by Guilouz** [comment]
Just updated my script by removing TLS error.

**Comment by Saberlord** [comment]
I just tried, seems like it is not the script issue. 

It seems like my board has some issues connecting to web addresses. Found out that the main error is 
" TLS error from peer (alert code 80): 80" and
"error getting response: Connection reset by peer"

not sure what caused the printer to get bad ports from web addresses but seems fine when I try to ping IP addresses. 

Tried resetting the printer, restore old firmware and updated but still stuck.

**Comment by Saberlord** [comment]
I have managed to split the install file and replaced the web pulls with direct transferring to the exact folder.

Thanks.

**Comment by MuaiyadTSB** [comment]
Getting same error here when pulling the script, same error occurs as well across the helper script if I move it manually. 

Pulling other files from other repositories, works fine.

Pulling the helper script works fine on the same network if I attempt to do it on my computer, but fails when attempting  to do it from the K1.

Manually installing entware and updating busybox and wget-ssl seems to fix the issue, but breaks mainsail/fluidd for some reason.

Thanks for all of your work.

<img width="769" alt="helper_script_error" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/99588776/1b0cd56e-3d5e-480e-8bee-7da104248532">

**Comment by Guilouz** [comment]
Try with this command: 

```
  cd && wget --no-check-certificate https://github.com/Guilouz/Creality-K1-and-K1-Max/raw/main/Scripts/installer.sh
  ```

**Comment by MuaiyadTSB** [comment]
I found the suggested command on multiple forums while trying troubleshoot, but it made no difference. Using raw github url seems to fix the issue for this repo, I created a pull request with the updated url in the script. It seems to resolve the issue for me.
