### ISSUE TITLE
[BUG]  python dependencies missing for input shaper

### ISSUE THREAD

**Issue by TheTesla** [Guilouz/Creality-K1-and-K1-Max#300]
### What happened?

Input shaper (with or without guppy screen) can't find numpy and fails.

### What did you expect to happen instead?

Input shaper should pass without errors.

### How to reproduce this issue?

Run input_shaper_calibration macro.

### Additional information:

numpy is missing in the `/usr/share/klippy-env`. Trying to install it ends in `[Errno 2] No such file or directory: '/opt/wuhui/code/creality/Pre-release/ingenic_linux_CR4CU220812S11/buildroot/buildroot/output/host/bin/mips-linux-gnu-gcc`

**Comment by Guilouz** [comment]
I don’t know what you have changed but inout shaper is working.

restore to factory and reinstall

**Comment by TheTesla** [comment]
How should I restore the factory settings?

**Comment by Guilouz** [comment]
Read the wiki…

**Comment by TheTesla** [comment]
OK, thanks. It works now, I restored to factory settings. Maybe I messed up the setup by installing byobu and tmux. I did everything in the byobu session...
