### ISSUE TITLE
[BUG] KAMP Line Purge purge a big dot at the center when do a PA calibration on Orca Slicer.

### ISSUE THREAD

**Issue by FunFunBoy** [Guilouz/Creality-K1-and-K1-Max#310]
### What happened?

KAMP Line Purge purge a big dot at the center when do a PA calibration on Orca Slicer.

### What did you expect to happen instead?

Draw  a pruge line as normal.

### How to reproduce this issue?

Do a PA calibration on Orca Slicer.

**Comment by jooslouw** [comment]
@FunFunBoy, check this [discussion](https://github.com/Guilouz/Creality-K1-and-K1-Max/discussions/260) on how to temporarily disable KAMP for a print.

**Comment by Guilouz** [comment]
Will be fixed in nest KAMP version.
