### ISSUE TITLE
[BUG] Camera fails mid print and timelapse renders partial clip

### ISSUE THREAD

**Issue by brightandshinyobject** [Guilouz/Creality-K1-and-K1-Max#314]
### What happened?

Following a factory reset and upgrade to 1.3.3.5 firmware., installation of helper script and the below configuration, the camera will stop streaming and being capturing corrupted frames.

### What did you expect to happen instead?

That the ai webcam will continue to stream and capture frames without failing mid print(print quality is unaffected), and remain usable without needing to reboot system between prints.

### How to reproduce this issue?

Performing a factory reset and installtion of helper script and the configuration in additional information. Will lead to the AI camera to stop streaming and timelapse no longer capturing valid frames.

### Additional information:

•ESSENTIALS:                                       
  Moonraker & Nginx → Installed                    
  Fluidd → Not Installed                           
  Mainsail → Installed                             
                                                   
•UTILITIES:                                        
  Entware → Installed                              
  Klipper Gcode Shell Command → Installed          
  Hostname Service → Installed                     
  Supervisor Lite → Installed                      
  Host Controls Support → Installed                
                                                   
•IMPROVEMENTS:                                     
  Klipper Adaptive Meshing & Purging → Installed   
  Buzzer Support → Not Installed                   
  Nozzle Cleaning Fan Control → Not Installed      
  Fans Control Macros → Not Installed              
  Improved Shapers Calibrations → Not Installed    
  Usefull Macros → Installed                       
  Save Z-Offset Macros → Installed                 
  Screws Tilt Adjust Support → Installed           
                                                   
•CAMERA:                                           
  Moonraker Timelapse → Installed                  
  Camera Settings Control → Not Installed          
                                                   
•REMOTE ACCESS AND AI DETECTION:                   
  OctoEverywhere → Not Installed                   
  Obico → Not Installed                            
  Mobileraker Companion → Not Installed            
                                                   
•CUSTOMIZATION:                                    
  Custom Boot Display → Not Installed              
  Creality Web Interface → Present                 
  Guppy Screen → Installed                         
  Creality Dynamic Logos for Fluidd → Not Installed

[bulbasaur_high_temp_PLA_13m10s.zip](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/14055819/bulbasaur_high_temp_PLA_13m10s.zip)
I don't know if it is related but the rpi mcu maxes out at 100% consistently when the issue occurs.
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/14224724/229b8134-f8d1-41fc-ae1c-3341bfad2f26)
     System: Linux (Kernel 4.4.94)                         
   Firmware: 1.3.3.5                                       
   Hostname: K1Max-4CEF                                    
 IP Address: 192.168.55.82 (WLAN)                          
  RAM Usage: 3 MB / 209 MB (1% available)                  
 Disk Usage: 367.5M / 6.5G (5.8G available)                
     Uptime: 0 days 1 hours 46 minutes                     
  Processes: 95 running process                            
System Load: 0.77 (1 min.) / 0.87 (5 min.) / 0.77 (15 min.)
[moonraker.log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/14055862/moonraker.log)
[klippy.log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/14055863/klippy.log)

**Comment by Guilouz** [comment]
The operation of the camera has nothing to do here.

Please only post Wiki-related issues.
