### ISSUE TITLE
[BUG] After firmware update to 1.3.3.5 the LCD does not show the printer menus (K1 and K1 Max)

### ISSUE THREAD

**Issue by mauroavello** [Guilouz/Creality-K1-and-K1-Max#328]
### What happened?

With firmware 1.3.3.5 both downloaded and ota, the lcd screen stops showing the creality menus after restarting the printer. So to reiterate, it shows the creality logo after start and you get a black screen and no menus. Happens on both, K1 and K1 Max. 
Have done a reset on both printers, as per instructions,  using the Creality_K1_Reset_Utility.
If you install guppy the screen comes back to life, but no luck using the standard screen.

### What did you expect to happen instead?

After showing the creality logo to show the printer menus

### How to reproduce this issue?

Update firmware to 1.3.3.5. Reset the printer with utility. Using helper script install:
* Moonraker and Nginx
* Fluidd (port 4408)
* Entware
* Klipper Gcode Shell Command
* Supervisor Lite
* Host Controls Support
* Klipper Adaptive Meshing & Purging
* Nozzle Cleaning Fan Control
* Fans Control Macros
* Improved Shapers Calibrations
* Usefull Macros
* Save Z-Offset Macros
* Screws Tilt Adjust Support
After restarting the printer the screen shows the Creality Logo but after bootup it won't show the printer menus.

**Comment by Guilouz** [comment]
I think you have missed something, all items in script are tested and working fine. Issue is on your side and not related to helper script.

Try to restart a factory settings.

**Comment by aken** [comment]
The bug can be reproduced by removing "Host Controls Support" and "Hostname Service" / restart.
To fix: install them back

**Comment by winbard** [comment]
Hi,
i have the firmware 1.3.3.5 on my K1Max too. And I install the same with the helper script.
It work.
I have make a Firmware Reset from the describtion in Wiki.
I look before that nothing is install from the helper script.
And I clear the cache before and after the install with the helper script.
What I only have after the first start an error in the screen after the first start.
But only one time.

**Comment by SuperultraCat** [comment]
I have the firmware 1.3.3.5 on K1 Max. Updated the firmware with a full reset.
After starting printing "/usr/bin/display-server" consumes all the free CPU time and the LCD screen is not responding. If just restart the service, there is a 50/50 chance that it will freeze again, and again...

**Comment by Guilouz** [comment]
Supervisor Lite have nothing to see with screen UI, it just control service for Moonraker.

**Comment by cesar-anjos** [comment]
I am also facing the same issue. Updated to 1.3.3.5 and everything was working fine. 
After updating the helper script and updating the components the screen stopped working as well.

In my case I didn't do the factory reset procedure on purpose

**Comment by Guilouz** [comment]
Factory Reset must be done **after** firmware update and **especially** if you use script.

**Comment by cesar-anjos** [comment]
Yeah I know but even after that the issue still remained.
I ended up reverting back to a non-ssh available firmware version, at which point the screen came back, then re-upgraded to 1.3.3.5 and re-installed the helper script and fluidd and the rest and the screen is currently working fine. Will report back if it end up going down again.

**Comment by Guilouz** [comment]
Ok no problem, I close issue if it's back to normal.

**Comment by kisslorand** [comment]
Starting from FW v1.3.3.3 display-server will freak out if the default bed mesh is larger than 7x7. It will throw an error at 7x7 but it will start. With a bed mesh of 6x6 it will start normally without any error.
It's another aspect to watch out for.

**Comment by januszwoj** [comment]
Hi.
I played around with your settings for "Bed Mesh". They work great.
In my case, it turned out that changing these settings in the "printer.cfg" file does not cause problems with the lack of image on the LCD.
Only making/adding a table map with more points than 6x6 causes the screen to be unable to load the firmware for some reason.
It's very easy to check this, just add something like this at the end of the file with the default settings:
```
#*# [bed_mesh Plate_A_1]
#*# version = 1
#*# points =
#*# 	  0.113812, 0.068969, 0.089656, 0.111375, 0.096844, 0.044719, 0.117645, 0.123531, 0.069000, 0.047906, 0.096406
#*# 	  0.143719, 0.086906, 0.059219, 0.086312, 0.092312, 0.065472, 0.089673, 0.090062, 0.066418, 0.068062, 0.088594
#*# 	  0.152844, 0.104531, 0.081906, 0.051250, 0.094656, 0.064895, 0.083969, 0.085562, 0.063969, 0.074719, 0.139886
#*# 	  0.204469, 0.116438, 0.096938, 0.083375, 0.097156, 0.104105, 0.113156, 0.053344, 0.078219, 0.093250, 0.178500
#*# 	  0.220574, 0.165156, 0.112438, 0.123014, 0.130437, 0.119594, 0.118281, 0.074000, 0.081750, 0.141062, 0.218472
#*# 	  0.201375, 0.144031, 0.095750, 0.103335, 0.121844, 0.167312, 0.107406, 0.036682, 0.157250, 0.164807, 0.193344
#*# 	  0.166963, 0.125562, 0.091875, 0.101170, 0.131502, 0.085651, 0.104165, 0.037906, 0.146193, 0.133031, 0.178500
#*# 	  0.120236, 0.111170, 0.086565, 0.097813, 0.103543, 0.074250, 0.082812, 0.068875, 0.119335, 0.113594, 0.141062
#*# 	  0.128500, 0.096281, 0.096156, 0.110719, 0.128543, 0.075662, 0.138528, 0.051912, 0.154344, 0.131813, 0.137000
#*# 	  0.092625, 0.064062, 0.120733, 0.132844, 0.096937, 0.070483, 0.089250, 0.021375, 0.104702, 0.108531, 0.182781
#*# 	  0.150969, 0.087062, 0.129187, 0.131781, 0.150304, 0.146094, 0.132344, 0.068219, 0.174639, 0.156594, 0.224080
#*# x_count = 11
#*# y_count = 11
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = bicubic
#*# tension = 0.2
#*# min_x = 5.0
#*# max_x = 295.0
#*# min_y = 5.0
#*# max_y = 295.0
#*#
```
This is a map of one of my plates made with a resolution of 11x11 points.
I hope this might be helpful.
