### ISSUE TITLE
Error in the macro name

### ISSUE THREAD

**Issue by denisapokin** [Guilouz/Creality-K1-and-K1-Max#33]
According to the link, there is an error in the macro name at the bottom of the page. https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Fix-issue-with-Input-Shaper
[Now run INPUT_SHAPPER macro, this will measure the X and Y axis resonances.]
Should be: 
[Now run INPUT_SHAPER macro, this will measure the X and Y axis resonances.]

Thank you for your work!

**Comment by Guilouz** [comment]
Thanks for report, it's fixed.
