### ISSUE TITLE
[BUG] <title>Script Helper install failed

### ISSUE THREAD

**Issue by Myklt8** [Guilouz/Creality-K1-and-K1-Max#355]
### What happened?

Get install failed error when sending command to run script

### What did you expect to happen instead?

Open Script Helper

### How to reproduce this issue?

install script helper 
run script helper

### Additional information:

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/126296783/ab6606cb-dd9e-4cd6-bd47-d6c375582d06)

**Comment by Guilouz** [comment]
That's mean your printer can't downloading curl package with this command:

```
wget -q --no-check-certificate https://raw.githubusercontent.com/Guilouz/Creality-K1-and-K1-Max/main/Scripts/files/fixes/curl -O /tmp/curl
```

**Comment by Myklt8** [comment]
I reset to factory again and it worked, but now can't install moonraker 
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/126296783/28fc6d28-1570-489b-bb0b-b5728a3645f7)

**Comment by Myklt8** [comment]
I think it was because you were updating at the same time I was installing...all good now, thank you

**Comment by Guilouz** [comment]
I think you have issue with your connection.
