### ISSUE TITLE
Klipper reports : ERROR after installing Fan Control Macro

### ISSUE THREAD

**Issue by f1cs2000** [Guilouz/Creality-K1-and-K1-Max#362]
### What happened?

After installing Nozzle Cleaning Fans Control if I add those 2 lines  in printer_params.cfg file:
[prtouch_v2_fan]
 max_speed: 0.5

I got this Error: 
{"code": "key341", "msg": "Section 'prtouch_v2_fan' is not a valid config section\n\nOnce the underlying issue is corrected, use the \"RESTART\"\ncommand to reload the config and restart the host software.\nPrinter is halted\n", "values": ["prtouch_v2_fan"]}

If I don't add the lines I have no error, but no change at the fan controller. As attach picture.

I tried to remove and reinstall ... Same thing

Any Idea?
![FAN](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/156813873/e7b88b28-d66f-4726-99b5-f1238424b98d)
[klippy(8).log](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/14163744/klippy.8.log)

### What did you expect to happen instead?

Had the new layout THERMALS

### How to reproduce this issue?

Installing Fan Nozzle Cleaning Fans Control

**Comment by Guilouz** [comment]
Fan Nozzle Cleaning Fans Control add nothing on Web UI and you don’t need to add something too, script install all necessary, and the job is done automatically.
