### ISSUE TITLE
Feature Request: tmc autotune

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#39]
Good morning,
would it be possible to include this function in the script?
I think it could help reduce Vfa. But I haven't tested it yet.

https://github.com/andrewmcgr/klipper_tmc_autotune/tree/main

**Comment by Nastras** [comment]
I just saw that it is a Python script. Then it probably doesn't work on the K1 or?
-.-

**Comment by joschiv1977** [comment]
This doesnt help you al lot. It`s only for LDO motors.

**Comment by Guilouz** [comment]
K1 motors are not referenced in Klipper TMC Autotune and we lack information on the motors to be able to add them.
