### ISSUE TITLE
Bad address 

### ISSUE THREAD

**Issue by Jakesss504** [Guilouz/Creality-K1-and-K1-Max#42]
Hey I’m trying to root my k1 max I did everything right but it won’t work 
![IMG_0057](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146686849/656c4536-f9a1-48ba-a011-2f00fefd7c19)

**Comment by joschiv1977** [comment]
cd && wget --no-check-certificate https://github.com/Guilouz/Creality-K1-and-K1-Max/raw/main/Scripts/installer.sh
