### ISSUE TITLE
Led on - off when start and end print

### ISSUE THREAD

**Issue by mindkill666** [Guilouz/Creality-K1-and-K1-Max#43]
Saw this on Facebook and i think it was very helpful.
Maybe  you can add this for other people to use.

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/129465886/c860452f-8393-4fc1-8806-e37e69b0d995)

**Comment by Guilouz** [comment]
This is a normal use of Klipper function, available here: https://www.klipper3d.org/fr/G-Codes.html#set_pin

So, there no interest to add this in Wiki.
