### ISSUE TITLE
I can't install Fluidd or Mainsail

### ISSUE THREAD

**Issue by AkiTsukita** [Guilouz/Creality-K1-and-K1-Max#45]
I'm had just install the latest firmware and I can't install Fluidd or Mainsail

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/71583222/e9d4649a-1907-4609-a6b6-805278946d6a)

**Comment by tuannat** [comment]
install Entware, use it install wget-ssl and try again

**Comment by Guilouz** [comment]
<img width="1492" alt="Capture d’écran 2023-10-02 à 21 42 26" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/7020d3b0-eaaa-4de3-8057-79385f87d090">


No issue for me, your error is elsewhere.
