### ISSUE TITLE
Lidar first layer scan

### ISSUE THREAD

**Issue by Hantse** [Guilouz/Creality-K1-and-K1-Max#47]
Hello,

I've root my K1 Max, and with initial version before printing K1 draw 4 line and scan with Lidar, after first layer print, the same happen, lidar scan.

It's possible to used it ? Macro already exist ?

Thank's !

**Comment by Guilouz** [comment]
You must use Creality Print Slicer for lidar calibration. This can't be used with other slicers.

First layer inspection working with all slicers.
