### ISSUE TITLE
Kamp recovery error

### ISSUE THREAD

**Issue by mindkill666** [Guilouz/Creality-K1-and-K1-Max#49]
After installing the new kamp fix, i get this on the update page.
Should i recover or let it be?
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/129465886/dcc13bfc-8286-4970-a9b6-bac8d9229cb0)

**Comment by joschiv1977** [comment]
If you recover KAMP won´t work again. Best for now, ignore it.

**Comment by Guilouz** [comment]
Yes remove kamp from update manager, it not must be updated
