### ISSUE TITLE
Unable to use OrcaProfiles

### ISSUE THREAD

**Issue by thuttu** [Guilouz/Creality-K1-and-K1-Max#5]
Starting of prints sliced with OrcaSlicer + profiles fails to errors 

10:21:47 
!! {"code":"key60", "msg":"Internal error on command:CX_PRINT_DRAW_ONE_LINE", "values": ["CX_PRINT_DRAW_ONE_LINE"]}
10:21:47 
!! {"code":"key60", "msg":"Internal error on command:START_PRINT", "values": ["START_PRINT"]}
10:42:20 
!! {"code":"key60", "msg":"Internal error on command:CX_PRINT_DRAW_ONE_LINE", "values": ["CX_PRINT_DRAW_ONE_LINE"]}
10:43:50 
$ RESTART
10:43:50 
// Klipper state: Disconnect

**Comment by Guilouz** [comment]
Wich fw version do you use ?

**Comment by thuttu** [comment]
I have rooted 1.3.1.19 with all the modifications from wiki, OS is Win 11 and 10 English with Finnish locale

**Comment by Guilouz** [comment]
It's look like you have an issue with your START_PRINT macro, check it.

**Comment by thuttu** [comment]
Well I as seeing some error somewhere which said that START_PRINT wants %d so decimal values but in gcode they are without decimals (int) also Gcode created with creality print works just fine.

**Comment by Guilouz** [comment]
I only use OrcaSlicer and it’s working fine.

**Comment by thuttu** [comment]
Finally got time to debug with printer it seems that if I upload and start print it fails, if I start print from fluidd it fails.
But if I start print from printers touch screen it works just fine.

**Comment by Guilouz** [comment]
Read the wiki…

**Comment by thuttu** [comment]
I just realized that there is 3 lines missing from start print.
