### ISSUE TITLE
Hostname changing in ssh but not connecting in browser

### ISSUE THREAD

**Issue by tinymachines3d** [Guilouz/Creality-K1-and-K1-Max#50]
@Guilouz, thanks for building the installer! With the Hostname Service file, after changing the hostname, how do you access the printer in browser? I can see my new host name in cli but when trying to go to hostname.local / not found. The router is showing it as ingenic-2C8C

My goal is to access multiple printers with their hostname instead of ip in chrome browser. 

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/28379694/798f8b6c-566d-4f06-866e-7ecc1586aa49)

I have cross posted on the aim6mac discord as well.

**Comment by Guilouz** [comment]
Is it fixed by modifying host file too ?
