### ISSUE TITLE
KAMP doesnt do a smaller bed mesh but just a regular one

### ISSUE THREAD

**Issue by Remleyfpv** [Guilouz/Creality-K1-and-K1-Max#53]
After following this guide and installing KAMP the K1 does a  full bed mesh every print. (I use orca slicer so I believe it should work no slicer changes right? as  I also see the"exclude object" button in mainsail)

**Comment by Guilouz** [comment]
You have missing something.

Do you have enabled enable_object_processing in moonraker.conf?

**Comment by joschiv1977** [comment]
Label objects must be on in your slicer

<img width="296" alt="image" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/139355048/0f18bff4-997f-4666-ac04-b0d146e365b0">

**Comment by Remleyfpv** [comment]
And 

> You have missing something.
> 
> Do you have enabled enable_object_processing in moonraker.conf?
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/103446008/af1486a4-8ea7-4504-81e2-00ed5ebe2fb9)

**Comment by joschiv1977** [comment]
> How do you do that in orcaslicer?

Search is the key 

<img width="319" alt="image" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/139355048/6d35643c-1fd4-4ce2-9569-216ba206413c">

<img width="311" alt="image" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/139355048/7ea32398-b1ad-43e1-91da-f1b227c779e6">

<img width="298" alt="image" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/139355048/c9f6d4c4-a94f-479a-a42b-9cefcec008ee">

**Comment by Remleyfpv** [comment]
Fixed! had to completely reload all firmware!
