### ISSUE TITLE
AI Camera not pausing print

### ISSUE THREAD

**Issue by TaylorN15** [Guilouz/Creality-K1-and-K1-Max#54]
I see alerts in the printer logs and in the Creality Cloud app when the AI camera detects issues, however, it doesn't pause the print. I can only assume this is due to the custom firmware etc.

Is there a way to get the printer to pause when it detects a failure?

**Comment by Guilouz** [comment]
Firmware is not a custom firmware, it’s official firmware provided by creality.

the AI ​​functions are therefore managed by the firmware, so it has nothing to do with my wiki. 

Please post issues only relating to the wiki.
