### ISSUE TITLE
KAMP issue

### ISSUE THREAD

**Issue by bhast2** [Guilouz/Creality-K1-and-K1-Max#56]
When I try to use Adapted mesh I get this error after it gets done creating the mesh.
```
08:12:49 AM 
!! {"code":"key60", "msg":"Internal error on command:_BED_MESH_CALIBRATE", "values": ["_BED_MESH_CALIBRATE"]}
08:12:49 AM 
!! {"code":"key60", "msg":"Internal error on command:BED_MESH_CALIBRATE", "values": ["BED_MESH_CALIBRATE"]}
08:12:49 AM 
!! {"code":"key60", "msg":"Internal error on command:START_PRINT", "values": ["START_PRINT"]}
```

I have followed the steps in the wiki and still get this error.

**Comment by Guilouz** [comment]
You must have missed something.

Uninstall KAMP and reinstall it, I simplified the installation in my latest version of the script that I just released. And see updated [Use KAMP](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Use-KAMP) section.

**Comment by kwotattoos** [comment]
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/143551310/f28f50df-bb63-4174-b246-7f089863ced6)

i uninstalled and reinstalled kamp and this is the error im getting

**Comment by Guilouz** [comment]
Remove kamp from update manager in moonraker.conf, it must not be updated with the fix.
