### ISSUE TITLE
Crowsnest for K1

### ISSUE THREAD

**Issue by Mallepi** [Guilouz/Creality-K1-and-K1-Max#57]
Hello and thank you for your work.
I am looking for a solution to integrate an Eufy Indoor 2K camera via RTSP in Mainsail.
I came across Crowsnest but I am not sure if it works with the K1. What do you think?
If so would it be possible that you support this tool in your script?

https://github.com/mainsail-crew/crowsnest

**Comment by joschiv1977** [comment]
https://github.com/trevos3d/K1-USB-Cam

**Comment by Guilouz** [comment]
Nope, Crowsnest can't work.
