### ISSUE TITLE
PrettyGCode

### ISSUE THREAD

**Issue by bhast2** [Guilouz/Creality-K1-and-K1-Max#59]
Anyway to add PrettyGCode to the script.

https://github.com/Kragrathea/pgcode

**Comment by joschiv1977** [comment]
running on K1 so far. have to do some tweaks.

<img width="1124" alt="image" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/139355048/a1b61812-2361-4ce3-96ec-825a0033a291">
