### ISSUE TITLE
Incorrect Cooling Fan Settings When Slicing in Orca Slicer

### ISSUE THREAD

**Issue by vformi** [Guilouz/Creality-K1-and-K1-Max#67]
I've noticed the printer doesn't follow the cooling fan settings I've configured in the Orca Slicer. Despite setting specific speeds (as shown in the attached image), the printer behaves differently during the print.
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/104455049/a051d5d3-a5ee-4b9b-93b6-a084ec4111d9)

**Comment by Guilouz** [comment]
Not related to my wiki.

Please post only issue related to the wiki here, it’s not a system help.
