### ISSUE TITLE
MobileRaker

### ISSUE THREAD

**Issue by elpigeondindo** [Guilouz/Creality-K1-and-K1-Max#68]
salut, deja super taf pour tous ces scripts reunis au meme endroit.

J'ai voulu installer mobileraker companion, tout se passe bien, mais quand je vais sur mon smartphone il arrive pas a se connecter a l'imprimante ou au socket. Il faut faire un truc en plus pour le faire fonctionner ?

Quelqu'un a deja reussi?
-------------------------------------------
hi, already great work for all these scripts gathered in the same place.

I wanted to install mobileraker companion, everything goes well, but when I go to my smartphone it cannot connect to the printer or the socket. Do I have to do something extra to make it work?

Has anyone already succeeded?

**Comment by joschiv1977** [comment]
you can open the url http://192.168.1.30:4409/ in your webbrowser on your phone ?

**Comment by elpigeondindo** [comment]
yes of course

**Comment by joschiv1977** [comment]
try https://192.168.1.30:4409 and make a check mark at trust self signing certificates in the mobileraker app

**Comment by elpigeondindo** [comment]
i can't acces to mainsail on HTTPS

**Comment by joschiv1977** [comment]
do it in the app

**Comment by elpigeondindo** [comment]
i try and i have this

connection refused (os error: connection refused, errno = 61), address = 192.168.1.30, port 49654

**Comment by elpigeondindo** [comment]
[https://i.ibb.co/S72W7Gg/IMG-2412.png](url)

a screenshot

**Comment by Guilouz** [comment]
Yu as oublié les ports dans tes adresses.

**Comment by elpigeondindo** [comment]
Oh put** quel nul ! comment j'ai pu oublié ca lol. Merci guillouz
