### ISSUE TITLE
Update Klipper?

### ISSUE THREAD

**Issue by AiramsRT** [Guilouz/Creality-K1-and-K1-Max#7]
Hello.  

First of all, thank you for the good work you have done rooting the Creality K1! I installed it yesterday and it worked great.  I have a question, I have seen that klipper is in version 0.9 on the printer, is it not possible to update it?  Especially to be able to use KAMP and Exclude object which is only possible in Klipper 0.11.  Thank you !!

**Comment by Guilouz** [comment]
Actually it's not possible to use official Klipper build.

**Comment by AiramsRT** [comment]
Ok Thanks!!

**Comment by Thrashin** [comment]
> Actually it's not possible to use official Klipper build.

Actually im pretty sure it is now possible https://github.com/mainsail-crew/creality-k1-klipper if you look through the files in the klipper you will find v0.11
