### ISSUE TITLE
Imput Shaper Fix not working

### ISSUE THREAD

**Issue by Myklt8** [Guilouz/Creality-K1-and-K1-Max#72]
The x axis gose first and is being overwritten by the Y. I did like the individual codes better. I am also getting this error 
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/126296783/0280d02d-d8fa-4460-85c8-a6209266acc0)

**Comment by Guilouz** [comment]
Can't reproduce this issue, working fine for me and for others people.

**Comment by Myklt8** [comment]
OK, I will try again
Thank you
