### ISSUE TITLE
input_shaper

### ISSUE THREAD

**Issue by ludo453** [Guilouz/Creality-K1-and-K1-Max#73]
Bonjour Cyril, 

Avec le dernier firmware j'ai les messages ci-dessous dans le input_shaper

!! {"code":"key60", "msg":"Internal error on command:M84", "values": ["M84"]}
15:04:03 
!! {"code":"key60", "msg":"Internal error on command:INPUT_SHAPER", "values": ["INPUT_SHAPER"]}

Je viens de voir que maintenant j'ai INPUTSHAPER et INPUT_SHAPER maintenant lequel prendre ?

**Comment by Nazgile94** [comment]
INPUT_SHAPER
is the custom macro 

---
i translating 👍

Hi Cyril,

With the latest firmware I have the following messages in the input_shaper

!! { "code": "key60", "msg": "Internal error on command:M84", "values": ["M84"]}
15:04:03
!! { "code": "key60", "msg": "Internal error on command:INPUT_SHAPER", "values": ["INPUT_SHAPER"]}

I just saw that now I have INPUTSHAPER and INPUT_SHAPER now which one to take?

**Comment by Guilouz** [comment]
You must use INPUT_SHAPER macro to run test manually.

**Comment by ludo453** [comment]
Ok it's him I take and he gives me the mistakes
