### ISSUE TITLE
orca pla profile not working

### ISSUE THREAD

**Issue by bodydropped72** [Guilouz/Creality-K1-and-K1-Max#75]
ive been trying to get a print to start using your pla profile and it gives me this error EVERY time   

13:18:08 
// {"code":"key111", "msg": "Extrude below minimum temp
// See the 'min_extrude_temp' config option for details", "values": []}
13:18:08 
!! {"code":"key111", "msg": "Extrude below minimum temp

also why does the extruder heat up then it homes to center of build plate then it cools down a significant amount then heats up again. this is where i believe the error is happening. ive followed your instruction to the T. The ABS profile works but it also does that thing where the extruder will heat up, then cool down then heat up again

**Comment by Guilouz** [comment]
This is how Creality Os works, temp is reduced during calibration. I have no issue with PLA.

**Comment by bodydropped72** [comment]
im using all of your profiles. every single time once it goes through
operating sequence and the print gets ready to start it stops on extruder
temp to low. i have not changed anything. Literally copy/pasted all of your
stuff. Ive printed with abs just fine btw

**Comment by aaronsmith1234** [comment]
As a note, I've had this same issue; used the profiles as provided, had exact same issues.... @Guilouz happy to help debug

**Comment by aaronsmith1234** [comment]
As a note, I added 
`min_extrude_temp: 170`
to the [extruder] section in printer.cfg, and had no change. The message still says:

`{"code":"key111", "msg": "Extrude below minimum temp
See the 'min_extrude_temp' config option for details", "values": []}`

which makes me think its not picking the value up correctly...

**Comment by aaronsmith1234** [comment]
@bodydropped72 were you able to resolve?

**Comment by bodydropped72** [comment]
If I remember correctly I went back to original root. Then I did something and went back but using a different profile in orca. Haven’t used machine in over a week due to hotend board failure. I’d have to check when I get it back up and runningRobby Mendel On Nov 14, 2023, at 7:49 PM, aaronsmith1234 ***@***.***> wrote:﻿
@bodydropped72 were you able to resolve?

**Comment by aaronsmith1234** [comment]
And as a note I am using OrcaSlicer v 1.8.0-rc2, and am on firmware version 1.3.2.1

**Comment by aaronsmith1234** [comment]
I can also confirm that if I use a different slicer\profile (namely PrusaSlicer), things work fine, so its either the slicer or the profile... @Guilouz what version of OrcaSlicer are you using?
