### ISSUE TITLE
Unable to find DBus PolKit Interface

### ISSUE THREAD

**Issue by thomazff** [Guilouz/Creality-K1-and-K1-Max#77]
Just flashed new firmware and started everything from scratch. Everything is working normally. But I got his in fluidd as a moonraker error. Mine is a K1.

Moonraker warnings found.
        Unable to find DBus PolKit Interface, this suggests PolKit is not installed on your OS.

**Comment by Guilouz** [comment]
Screenshot please

**Comment by thomazff** [comment]
Hi, you can close this issue. It was probably nothing to do with the script. I hit the reset los and all on the screen of the printer and installed everything from scratch and it never showed again.

Apreciate the atention. Thanks for the script.
