### ISSUE TITLE
Some strange things, I found, during the work (Timelapse and Mainsail)

### ISSUE THREAD

**Issue by ACKET2009** [Guilouz/Creality-K1-and-K1-Max#78]
1) In Mainsail I can not create a 2 different profiles, they stored all wit a one profilename and with the same parameters
2) In mainsail I can not choose the videocamera the parameter is unaccessible
3) After the installing the timelapse, I trying to make the video shots from the orcaslicer, but, after the first layer, the printhead kick to the far left corner of a printer and the layer shifted. I do not check the parameter with the head movement each layer - only make a shot....

P.S. 1) Can You make the KAMP module to check updates from the repository?
       2) Can You make the autotune settings for the K1 Max drives and add this tto a wiki?
Thank You for Your Great job!!!

**Comment by Guilouz** [comment]
Please only post issue related to the Wiki. There is a Discussion section for help.

Your issue with timelapse it's just configuration.

KAMP can't be updated because it's a modified version to work with K1.
TMC Autotune have not referenced K1 motors.
