### ISSUE TITLE
Backup in script 3.1 doesn't work

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#82]
I noticed that the backup function in the script only creates a file with 0 bytes and no content.
I've tried several times, always the same result.

Has there been an error?

<img width="538" alt="Bildschirmfoto 2023-10-26 um 11 40 32" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/79418c9a-aa00-42e7-a725-3d29465f2f26">

**Comment by Guilouz** [comment]
There is no change in backup since many updates.
What is the result when backup in script ?

**Comment by Nastras** [comment]
No free memory. I missed the message. The question is why is there no memory?

<img width="662" alt="Bildschirmfoto 2023-10-26 um 11 48 39" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/c1269307-30d2-40ae-be31-1d25931fe30b">
<img width="662" alt="Bildschirmfoto 2023-10-26 um 11 50 43" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/27686185/77a289f0-d510-455a-ac88-065e44f71500">

**Comment by Guilouz** [comment]
It's you root partition is full. I don't know what exactly you did to get there but I think that to find something correct you will have to reset to factory

**Comment by Nastras** [comment]
Thanks for the tip. I am surprised that the memory for root is used up because I have nothing there except a mini script. The only thing that is there additionally is data from the usb cam tool.

I will check it later when I am at home and report.

**Comment by Nastras** [comment]
You were right. I have now deleted the USB Cam Tool which is stored in the root folder. After that I could make the backup normally because there is enough space again. I think the tool should not be stored in the root folder if the space is so small.


Would it actually be possible that you integrate the root folder into the backup for your own scripts?
