### ISSUE TITLE
Want to bed level before each print

### ISSUE THREAD

**Issue by grrminator** [Guilouz/Creality-K1-and-K1-Max#83]
Sorry to bug and this seems like a stupid question, but for the bed leveling to start EACH print while using orcaslicer,

Should I put BED_LEVELING in the start machine gcode?

Thanks

**Comment by Guilouz** [comment]
Not needed, it's already done by START_PRINT macro

**Comment by grrminator** [comment]
Are you sure? My print hasnt autoleveled once since the initial self test.

**Comment by Guilouz** [comment]
If you config files are up to date yes leveling is launched by CX_PRINT_LEVELING_CALIBRATION command in START_PRINT macro.

**Comment by grrminator** [comment]
But it doesnt do it ever. I see it there.
