### ISSUE TITLE
Chamber Fan during nozzle cleaning / calibration

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [Guilouz/Creality-K1-and-K1-Max#85]
Is there a way to turn off the chamber fan during the nozzle cleaning / calibration process?
The wiki only says how to set the max speed of all fans.

**Comment by joschiv1977** [comment]
Smae here. Read the wiki

[Control fans when cleaning the nozzle](https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Improve-Fans-Control#control-fans-when-cleaning-the-nozzle)

**Comment by Unkn0wn-MDCLXIV** [comment]
That does not tell me how to disable the chamber fan when the print starts.
It always spins at 100% at first when I start a print.

**Comment by Guilouz** [comment]
You can control chamber fan with temperature : https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Improve-Fans-Control#control-chamber-fan
