### ISSUE TITLE
100% Fan speed at the last few layers

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [Guilouz/Creality-K1-and-K1-Max#86]
My fan speed increases to 100% when the print is nearly finished. Is there a way to stop that?

**Comment by joschiv1977** [comment]
https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Improve-Fans-Control

**Comment by Unkn0wn-MDCLXIV** [comment]
I'm not talking about the cooling macro after the print is finished.
The speed of the fan increases when the print is close to finish, just for the last few layers.

**Comment by Guilouz** [comment]
It’s related to your gcode.

Please only post issue related to the wiki. For help you can use Discussion section
