### ISSUE TITLE
camera in mainsail

### ISSUE THREAD

**Issue by bhast2** [Guilouz/Creality-K1-and-K1-Max#88]
Can't not select camera for timelapse in mainsail.

**Comment by joschiv1977** [comment]
Setup your webcam (read the wiki) and you are good to go. you cant select the webcam in the settings of Timelapse. This is normal for Mainsail on the K1. 
![grafik](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/139355048/0931ea55-a7ae-403f-bf7f-144824996265)
