### ISSUE TITLE
Chamber Fan control doesn work

### ISSUE THREAD

**Issue by bronsn** [Guilouz/Creality-K1-and-K1-Max#91]
Hello,
your Script is great i like it but i have an Issue with the Control of the Chamber Fan.
I add the lines in the printer.cfg like you said and also the M141 in the gcode_macro_cgf andf i can adjust it in the Dashboard but the problem is, it shows that the fan is running but he isnt?

Also if the Temp is lower than i have adjust it looks like he is running at 100% you see at the pic, but in real the fan doesn not work.

![fan](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/117449088/93ba92ae-4583-431a-91b4-adfc9c2f7c40)

**Comment by Guilouz** [comment]
As you can see I can't reproduce this issue : 

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/8966503b-cafb-410e-99b2-5b21ec90a493)

When temp is under target temp fan is off and only on when temp is reached target temp.
