### ISSUE TITLE
EOL error after  updating kamp[BUG] <title>

### ISSUE THREAD

**Issue by mindkill666** [Guilouz/Creality-K1-and-K1-Max#94]
### What happened?

After updating kamp (smartpark.cfg) i get an eol error on line 1 after restart.
I found it is in the smartpark.cfg, i had to comment the smart park function in kamp.cfg to be able to run.

### What did you expect to happen instead?

expected to work normal

### How to reproduce this issue?

update kamp in the update menu in fluidd, got eol error on firmware restart

**Comment by mindkill666** [comment]
![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/129465886/a8a6f946-0329-4823-b635-ad7088840c9f)

**Comment by MuaiyadTSB** [comment]
ssh into your printer and modify line 13,14 in /usr/data/KAMP-for-K1-Series/Configuration/Smart_Park.cfg 

from: 

{% set center_x = bed_x_max / 2 | %}
{% set center_y = bed_y_max / 2 | %}

to:

{% set center_x = bed_x_max / 2 | float %}
{% set center_y = bed_y_max / 2 | float %}

**Comment by Guilouz** [comment]
A mistake. It's fixed. Thanks.
